[[microprofile]]
== Microprofile Specification Dependencies Mapping

This section details all dependencies related to Microprofile.

[[MicroProfile-Open-Tracing]]
=== `MicroProfile-Open-Tracing`

[[microprofile-opentracing]]
==== *microprofile-opentracing*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-opentracing</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-opentracing]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-opentracing*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>microprofile - opentracing</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-opentracing</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[]]
==== **
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[microprofile-opentracing-api]]
==== *microprofile-opentracing-api*
**Version**: 2.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.opentracing</groupId>
    <artifactId>microprofile-opentracing-api</artifactId>
    <version>2.0</version>
</dependency>
----
[[org.eclipse.microprofile.opentracing]]
==== *org.eclipse.microprofile.opentracing*
**Version**: 2.0.0

[source,xml]
----
<dependency>
    <groupId>microprofile opentracing bundle</groupId>
    <artifactId>org.eclipse.microprofile.opentracing</artifactId>
    <version>2.0.0</version>
</dependency>
----
[[microprofile-opentracing-repackaged]]
==== *microprofile-opentracing-repackaged*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>microprofile-opentracing-repackaged</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.packager.microprofile-opentracing-repackaged]]
==== *fish.payara.server.internal.packager.microprofile-opentracing-repackaged*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>repackaged microprofile opentracing</groupId>
    <artifactId>fish.payara.server.internal.packager.microprofile-opentracing-repackaged</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[MicroProfile-Open-API]]
=== `MicroProfile-Open-API`

[[]]
==== **
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[microprofile-openapi-api]]
==== *microprofile-openapi-api*
**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.openapi</groupId>
    <artifactId>microprofile-openapi-api</artifactId>
    <version>2.0.1</version>
</dependency>
----
[[org.eclipse.microprofile.openapi]]
==== *org.eclipse.microprofile.openapi*
**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>microprofile openapi bundle</groupId>
    <artifactId>org.eclipse.microprofile.openapi</artifactId>
    <version>2.0.1</version>
</dependency>
----
[[microprofile-opentracing-api]]
==== *microprofile-opentracing-api*
**Version**: 2.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.opentracing</groupId>
    <artifactId>microprofile-opentracing-api</artifactId>
    <version>2.0</version>
</dependency>
----
[[org.eclipse.microprofile.opentracing]]
==== *org.eclipse.microprofile.opentracing*
**Version**: 2.0.0

[source,xml]
----
<dependency>
    <groupId>microprofile opentracing bundle</groupId>
    <artifactId>org.eclipse.microprofile.opentracing</artifactId>
    <version>2.0.0</version>
</dependency>
----
[[microprofile-openapi]]
==== *microprofile-openapi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-openapi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-openapi]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-openapi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>microprofile - openapi</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-openapi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[MicroProfile-Rest-Client]]
=== `MicroProfile-Rest-Client`

[[]]
==== **
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[org.glassfish.jersey.ext.microprofile.]]
==== *org.glassfish.jersey.ext.microprofile.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-mp-rest-client</groupId>
    <artifactId>org.glassfish.jersey.ext.microprofile.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[microprofile-rest-client-api]]
==== *microprofile-rest-client-api*
**Version**: 2.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.rest.client</groupId>
    <artifactId>microprofile-rest-client-api</artifactId>
    <version>2.0</version>
</dependency>
----
[[org.eclipse.microprofile.rest.client]]
==== *org.eclipse.microprofile.rest.client*
**Version**: 2.0.0

[source,xml]
----
<dependency>
    <groupId>microprofile rest client bundle</groupId>
    <artifactId>org.eclipse.microprofile.rest.client</artifactId>
    <version>2.0.0</version>
</dependency>
----
[[microprofile-rest-client]]
==== *microprofile-rest-client*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-rest-client</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-rest-client]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-rest-client*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>microprofile rest client</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-rest-client</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[MicroProfile-Config]]
=== `MicroProfile-Config`

[[]]
==== **
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[microprofile-config-api]]
==== *microprofile-config-api*
**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.config</groupId>
    <artifactId>microprofile-config-api</artifactId>
    <version>2.0.1</version>
</dependency>
----
[[org.eclipse.microprofile.config]]
==== *org.eclipse.microprofile.config*
**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>microprofile config api</groupId>
    <artifactId>org.eclipse.microprofile.config</artifactId>
    <version>2.0.1</version>
</dependency>
----
[[microprofile-config]]
==== *microprofile-config*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-config</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-config]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-config*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>microprofile-config</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-config</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[microprofile-config-extensions]]
==== *microprofile-config-extensions*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-config-extensions</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-config-extensions]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-config-extensions*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>microprofile-config-extensions</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-config-extensions</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[microprofile-config-service]]
==== *microprofile-config-service*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>microprofile-config-service</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.microprofile-config-service]]
==== *fish.payara.server.internal.payara-modules.microprofile-config-service*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>microprofile config service</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.microprofile-config-service</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[MicroProfile-Fault-Tolerance]]
=== `MicroProfile-Fault-Tolerance`

[[]]
==== **
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[microprofile-fault-tolerance]]
==== *microprofile-fault-tolerance*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-fault-tolerance</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-fault-tolerance]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-fault-tolerance*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>microprofile - fault tolerance</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-fault-tolerance</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[microprofile-fault-tolerance-api]]
==== *microprofile-fault-tolerance-api*
**Version**: 3.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.fault-tolerance</groupId>
    <artifactId>microprofile-fault-tolerance-api</artifactId>
    <version>3.0</version>
</dependency>
----
[[org.eclipse.microprofile.fault.tolerance]]
==== *org.eclipse.microprofile.fault.tolerance*
**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>microprofile-fault-tolerance-api</groupId>
    <artifactId>org.eclipse.microprofile.fault.tolerance</artifactId>
    <version>3.0.0</version>
</dependency>
----
[[MicroProfile-Metrics]]
=== `MicroProfile-Metrics`

[[microprofile-metrics]]
==== *microprofile-metrics*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-metrics</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-metrics]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-metrics*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>microprofile - metrics</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-metrics</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[]]
==== **
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[microprofile-metrics-api]]
==== *microprofile-metrics-api*
**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.metrics</groupId>
    <artifactId>microprofile-metrics-api</artifactId>
    <version>3.0.1</version>
</dependency>
----
[[org.eclipse.microprofile.metrics]]
==== *org.eclipse.microprofile.metrics*
**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>microprofile metrics bundle</groupId>
    <artifactId>org.eclipse.microprofile.metrics</artifactId>
    <version>3.0.1</version>
</dependency>
----
[[MicroProfile-JWT-Propagation]]
=== `MicroProfile-JWT-Propagation`

[[]]
==== **
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[MicroProfile-Health]]
=== `MicroProfile-Health`

[[]]
==== **
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId></groupId>
    <artifactId></artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[microprofile-health-api]]
==== *microprofile-health-api*
**Version**: 3.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.health</groupId>
    <artifactId>microprofile-health-api</artifactId>
    <version>3.1</version>
</dependency>
----
[[org.eclipse.microprofile.health]]
==== *org.eclipse.microprofile.health*
**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>microprofile health check bundle</groupId>
    <artifactId>org.eclipse.microprofile.health</artifactId>
    <version>3.1.0</version>
</dependency>
----
[[microprofile-healthcheck]]
==== *microprofile-healthcheck*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-healthcheck</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.microprofile-healthcheck]]
==== *fish.payara.server.internal.payara-appserver-modules.microprofile-healthcheck*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>microprofile - healthcheck</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.microprofile-healthcheck</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[CDI]]
=== `CDI`

[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta cdi</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta cdi</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta cdi</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[payara-micro-cdi]]
==== *payara-micro-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-micro-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[payara-micro-cdi]]
==== *payara-micro-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-micro-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi]]
==== *fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>payara micro cdi</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi]]
==== *fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>payara micro cdi</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jersey-cdi1x]]
==== *jersey-cdi1x*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-cdi1x]]
==== *jersey-cdi1x*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[cdi-api-fragment]]
==== *cdi-api-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>cdi-api-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cdi-api-fragment]]
==== *cdi-api-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>cdi-api-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cdi-api-fragment]]
==== *cdi-api-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>cdi-api-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[gf-weld-connector]]
==== *gf-weld-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>gf-weld-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.gf-weld-connector]]
==== *fish.payara.server.internal.web.gf-weld-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>weld connector for glassfish</groupId>
    <artifactId>fish.payara.server.internal.web.gf-weld-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[tyrus-container-glassfish-cdi]]
==== *tyrus-container-glassfish-cdi*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-cdi</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[tyrus-container-glassfish-cdi]]
==== *tyrus-container-glassfish-cdi*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-cdi</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.container-glassfish-cdi]]
==== *org.glassfish.tyrus.container-glassfish-cdi*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus cdi component provider</groupId>
    <artifactId>org.glassfish.tyrus.container-glassfish-cdi</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.container-glassfish-cdi]]
==== *org.glassfish.tyrus.container-glassfish-cdi*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus cdi component provider</groupId>
    <artifactId>org.glassfish.tyrus.container-glassfish-cdi</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[hibernate-validator-cdi]]
==== *hibernate-validator-cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[hibernate-validator-cdi]]
==== *hibernate-validator-cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[org.hibernate.validator.cdi]]
==== *org.hibernate.validator.cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>hibernate validator portable extension</groupId>
    <artifactId>org.hibernate.validator.cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[org.hibernate.validator.cdi]]
==== *org.hibernate.validator.cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>hibernate validator portable extension</groupId>
    <artifactId>org.hibernate.validator.cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-transaction</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-transaction</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-servlet]]
==== *jersey-cdi1x-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-servlet]]
==== *jersey-cdi1x-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-servlet</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-servlet</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[cdi-auth-roles]]
==== *cdi-auth-roles*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>cdi-auth-roles</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cdi-auth-roles]]
==== *cdi-auth-roles*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>cdi-auth-roles</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles]]
==== *fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi auth: roles</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles]]
==== *fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi auth: roles</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cdieventbus-notifier-console-plugin]]
==== *cdieventbus-notifier-console-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>cdieventbus-notifier-console-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cdieventbus-notifier-console-plugin]]
==== *cdieventbus-notifier-console-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>cdieventbus-notifier-console-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin]]
==== *fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi event bus notifier console plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin]]
==== *fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi event bus notifier console plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[opentracing-cdi]]
==== *opentracing-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[opentracing-cdi]]
==== *opentracing-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.opentracing-cdi]]
==== *fish.payara.server.internal.payara-appserver-modules.opentracing-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>opentracing cdi</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.opentracing-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.opentracing-cdi]]
==== *fish.payara.server.internal.payara-appserver-modules.opentracing-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>opentracing cdi</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.opentracing-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[weld-integration-fragment]]
==== *weld-integration-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.weld-integration-fragment]]
==== *fish.payara.server.internal.web.weld-integration-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>weld integration fragment</groupId>
    <artifactId>fish.payara.server.internal.web.weld-integration-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[weld-integration]]
==== *weld-integration*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.weld-integration]]
==== *fish.payara.server.internal.web.weld-integration*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>weld integration for glassfish</groupId>
    <artifactId>fish.payara.server.internal.web.weld-integration</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[notification-cdi-eventbus-core]]
==== *notification-cdi-eventbus-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-cdi-eventbus-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[notification-cdi-eventbus-core]]
==== *notification-cdi-eventbus-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-cdi-eventbus-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core]]
==== *fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi eventbus notification implementation</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core]]
==== *fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi eventbus notification implementation</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[weld-ejb]]
==== *weld-ejb*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-ejb</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-jsf]]
==== *weld-jsf*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-jta]]
==== *weld-jta*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jta</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-web]]
==== *weld-web*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-web</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-probe-core]]
==== *weld-probe-core*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.probe</groupId>
    <artifactId>weld-probe-core</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-api]]
==== *weld-api*
**Version**: 3.1.sp4

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-api</artifactId>
    <version>3.1.sp4</version>
</dependency>
----
[[weld-core-impl]]
==== *weld-core-impl*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-core-impl</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-osgi-bundle]]
==== *weld-osgi-bundle*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-osgi-bundle</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-spi]]
==== *weld-spi*
**Version**: 3.1.sp4

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-spi</artifactId>
    <version>3.1.sp4</version>
</dependency>
----
[[org.jboss.weld.osgi-bundle]]
==== *org.jboss.weld.osgi-bundle*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>weld osgi bundle</groupId>
    <artifactId>org.jboss.weld.osgi-bundle</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[JSON-P]]
=== `JSON-P`

[[jackson-dataformat-xml]]
==== *jackson-dataformat-xml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.dataformat.jackson-dataformat-xml]]
==== *com.fasterxml.jackson.dataformat.jackson-dataformat-xml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-dataformat-xml</groupId>
    <artifactId>com.fasterxml.jackson.dataformat.jackson-dataformat-xml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-module-jaxb-annotations]]
==== *jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.module.jackson-module-jaxb-annotations]]
==== *com.fasterxml.jackson.module.jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson module: old jaxb annotations (javax.xml.bind)</groupId>
    <artifactId>com.fasterxml.jackson.module.jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jersey-media-json-jackson]]
==== *jersey-media-json-jackson*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-jackson</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-jackson</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jackson-databind]]
==== *jackson-databind*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.core.]]
==== *com.fasterxml.jackson.core.*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-databind</groupId>
    <artifactId>com.fasterxml.jackson.core.</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jersey-media-json-processing]]
==== *jersey-media-json-processing*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-json-processing]]
==== *jersey-media-json-processing*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jsonp-jaxrs]]
==== *jsonp-jaxrs*
**Version**: 1.1.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jsonp-jaxrs</artifactId>
    <version>1.1.6</version>
</dependency>
----
[[org.glassfish.jsonp-jaxrs]]
==== *org.glassfish.jsonp-jaxrs*
**Version**: 1.1.5

[source,xml]
----
<dependency>
    <groupId>jakarta json processing media for jakarta restful web services</groupId>
    <artifactId>org.glassfish.jsonp-jaxrs</artifactId>
    <version>1.1.5</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-processing</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-processing</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jackson-annotations]]
==== *jackson-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.core.jackson-annotations]]
==== *com.fasterxml.jackson.core.jackson-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-annotations</groupId>
    <artifactId>com.fasterxml.jackson.core.jackson-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-core]]
==== *jackson-core*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.core.jackson-core]]
==== *com.fasterxml.jackson.core.jackson-core*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-core</groupId>
    <artifactId>com.fasterxml.jackson.core.jackson-core</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-dataformat-yaml]]
==== *jackson-dataformat-yaml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-yaml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.dataformat.jackson-dataformat-yaml]]
==== *com.fasterxml.jackson.dataformat.jackson-dataformat-yaml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-dataformat-yaml</groupId>
    <artifactId>com.fasterxml.jackson.dataformat.jackson-dataformat-yaml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-core]]
==== *jackson-core*
**Version**: 2.12.1

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.12.1</version>
</dependency>
----
[[JAX-RS]]
=== `JAX-RS`

[[jersey-media-multipart]]
==== *jersey-media-multipart*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-multipart</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-multipart</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-media-json-jackson]]
==== *jersey-media-json-jackson*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-jackson</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-jackson</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-mvc]]
==== *jersey-mvc*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-mvc]]
==== *org.glassfish.jersey.ext.jersey-mvc*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-mvc</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-mvc</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-media-jaxb]]
==== *jersey-media-jaxb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-jaxb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-jaxb</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-mvc-connector]]
==== *jersey-mvc-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jersey-mvc-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.jersey-mvc-connector]]
==== *fish.payara.server.internal.web.jersey-mvc-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jersey mvc tld connector implementation module</groupId>
    <artifactId>fish.payara.server.internal.web.jersey-mvc-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jersey-hk2]]
==== *jersey-hk2*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.inject</groupId>
    <artifactId>jersey-hk2</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.inject.jersey-hk2]]
==== *org.glassfish.jersey.inject.jersey-hk2*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-inject-hk2</groupId>
    <artifactId>org.glassfish.jersey.inject.jersey-hk2</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-mvc-jsp]]
==== *jersey-mvc-jsp*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc-jsp</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-mvc-jsp]]
==== *org.glassfish.jersey.ext.jersey-mvc-jsp*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-mvc-jsp</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-mvc-jsp</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-client]]
==== *jersey-client*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-client</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.core.jersey-client]]
==== *org.glassfish.jersey.core.jersey-client*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-core-client</groupId>
    <artifactId>org.glassfish.jersey.core.jersey-client</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-cdi1x]]
==== *jersey-cdi1x*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-media-json-binding]]
==== *jersey-media-json-binding*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-binding</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jaxrs-client-tracing]]
==== *jaxrs-client-tracing*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jaxrs-client-tracing</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.jaxrs-client-tracing]]
==== *fish.payara.server.internal.payara-appserver-modules.jaxrs-client-tracing*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>payara jax-rs client tracing</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.jaxrs-client-tracing</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jersey-media-moxy]]
==== *jersey-media-moxy*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-moxy</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-moxy</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-mp-rest-client]]
==== *jersey-mp-rest-client*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.microprofile</groupId>
    <artifactId>jersey-mp-rest-client</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.microprofile.]]
==== *org.glassfish.jersey.ext.microprofile.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-mp-rest-client</groupId>
    <artifactId>org.glassfish.jersey.ext.microprofile.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-proxy-client]]
==== *jersey-proxy-client*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-proxy-client</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-proxy-client]]
==== *org.glassfish.jersey.ext.jersey-proxy-client*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-proxy-client</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-proxy-client</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-media-json-processing]]
==== *jersey-media-json-processing*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jsonp-jaxrs]]
==== *jsonp-jaxrs*
**Version**: 1.1.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jsonp-jaxrs</artifactId>
    <version>1.1.6</version>
</dependency>
----
[[org.glassfish.jsonp-jaxrs]]
==== *org.glassfish.jsonp-jaxrs*
**Version**: 1.1.5

[source,xml]
----
<dependency>
    <groupId>jakarta json processing media for jakarta restful web services</groupId>
    <artifactId>org.glassfish.jsonp-jaxrs</artifactId>
    <version>1.1.5</version>
</dependency>
----
[[jersey-common]]
==== *jersey-common*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-common</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.core.jersey-common]]
==== *org.glassfish.jersey.core.jersey-common*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-core-common</groupId>
    <artifactId>org.glassfish.jersey.core.jersey-common</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-processing</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-server]]
==== *jersey-server*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-server</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-gf-ejb]]
==== *jersey-gf-ejb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers.glassfish</groupId>
    <artifactId>jersey-gf-ejb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.glassfish.]]
==== *org.glassfish.jersey.containers.glassfish.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-gf-ejb</groupId>
    <artifactId>org.glassfish.jersey.containers.glassfish.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.core.jersey-server]]
==== *org.glassfish.jersey.core.jersey-server*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-core-server</groupId>
    <artifactId>org.glassfish.jersey.core.jersey-server</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-transaction</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-bean-validation]]
==== *jersey-bean-validation*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-bean-validation</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-bean-validation]]
==== *org.glassfish.jersey.ext.jersey-bean-validation*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-bean-validation</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-bean-validation</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-servlet]]
==== *jersey-cdi1x-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-sse]]
==== *jersey-media-sse*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-sse</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-sse</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-servlet</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-entity-filtering]]
==== *jersey-entity-filtering*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-entity-filtering</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-entity-filtering]]
==== *org.glassfish.jersey.ext.jersey-entity-filtering*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-entity-filtering</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-entity-filtering</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-container-servlet-core]]
==== *jersey-container-servlet-core*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet-core</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.]]
==== *org.glassfish.jersey.containers.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-container-servlet-core</groupId>
    <artifactId>org.glassfish.jersey.containers.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-container-servlet]]
==== *jersey-container-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.]]
==== *org.glassfish.jersey.containers.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-container-servlet</groupId>
    <artifactId>org.glassfish.jersey.containers.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-container-grizzly2-http]]
==== *jersey-container-grizzly2-http*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-grizzly2-http</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.]]
==== *org.glassfish.jersey.containers.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-container-grizzly2-http</groupId>
    <artifactId>org.glassfish.jersey.containers.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[JAX-B]]
=== `JAX-B`

[[jackson-module-jaxb-annotations]]
==== *jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.module.jackson-module-jaxb-annotations]]
==== *com.fasterxml.jackson.module.jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson module: old jaxb annotations (javax.xml.bind)</groupId>
    <artifactId>com.fasterxml.jackson.module.jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[opentracing-jaxws]]
==== *opentracing-jaxws*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-jaxws</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[opentracing-jaxws]]
==== *opentracing-jaxws*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-jaxws</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws]]
==== *fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>opentracing jax-ws</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws]]
==== *fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>opentracing jax-ws</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta xml web services api</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta xml web services api</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.ws.rs-api]]
==== *jakarta.ws.rs-api*
**Version**: 2.1.6

[source,xml]
----
<dependency>
    <groupId>jakarta.ws.rs</groupId>
    <artifactId>jakarta.ws.rs-api</artifactId>
    <version>2.1.6</version>
</dependency>
----
[[jersey-media-jaxb]]
==== *jersey-media-jaxb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-jaxb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-jaxb</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jakarta.jws-api]]
==== *jakarta.jws-api*
**Version**: 1.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.jws</groupId>
    <artifactId>jakarta.jws-api</artifactId>
    <version>1.1.1</version>
</dependency>
----
[[jakarta.jws-api]]
==== *jakarta.jws-api*
**Version**: 1.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.jws api</groupId>
    <artifactId>jakarta.jws-api</artifactId>
    <version>1.1.1</version>
</dependency>
----
[[org.eclipse.persistence.dbws]]
==== *org.eclipse.persistence.dbws*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink dbws</groupId>
    <artifactId>org.eclipse.persistence.dbws</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[stax2-api]]
==== *stax2-api*
**Version**: 4.2.1

[source,xml]
----
<dependency>
    <groupId>org.codehaus.woodstox</groupId>
    <artifactId>stax2-api</artifactId>
    <version>4.2.1</version>
</dependency>
----
[[stax2-api]]
==== *stax2-api*
**Version**: 4.2.1

[source,xml]
----
<dependency>
    <groupId>stax2 api</groupId>
    <artifactId>stax2-api</artifactId>
    <version>4.2.1</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta xml binding api</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jaxb-runtime]]
==== *jaxb-runtime*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[txw2]]
==== *txw2*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>txw2</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[jaxb-xjc]]
==== *jaxb-xjc*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-xjc</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[codemodel]]
==== *codemodel*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>codemodel</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[xsom]]
==== *xsom*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>xsom</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[jaxb-jxc]]
==== *jaxb-jxc*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-jxc</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[istack-commons-runtime]]
==== *istack-commons-runtime*
**Version**: 3.0.12

[source,xml]
----
<dependency>
    <groupId>com.sun.istack</groupId>
    <artifactId>istack-commons-runtime</artifactId>
    <version>3.0.12</version>
</dependency>
----
[[istack-commons-tools]]
==== *istack-commons-tools*
**Version**: 3.0.12

[source,xml]
----
<dependency>
    <groupId>com.sun.istack</groupId>
    <artifactId>istack-commons-tools</artifactId>
    <version>3.0.12</version>
</dependency>
----
[[relaxng-datatype]]
==== *relaxng-datatype*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind.external</groupId>
    <artifactId>relaxng-datatype</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[rngom]]
==== *rngom*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind.external</groupId>
    <artifactId>rngom</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[dtd-parser]]
==== *dtd-parser*
**Version**: 1.4.5

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.dtd-parser</groupId>
    <artifactId>dtd-parser</artifactId>
    <version>1.4.5</version>
</dependency>
----
[[fastinfoset]]
==== *fastinfoset*
**Version**: 1.2.18

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.fastinfoset</groupId>
    <artifactId>fastinfoset</artifactId>
    <version>1.2.18</version>
</dependency>
----
[[stax-ex]]
==== *stax-ex*
**Version**: 1.8.3

[source,xml]
----
<dependency>
    <groupId>org.jvnet.staxex</groupId>
    <artifactId>stax-ex</artifactId>
    <version>1.8.3</version>
</dependency>
----
[[jaxb-osgi]]
==== *jaxb-osgi*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-osgi</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[com.sun.xml.bind.jaxb-osgi]]
==== *com.sun.xml.bind.jaxb-osgi*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>jaxb osgi</groupId>
    <artifactId>com.sun.xml.bind.jaxb-osgi</artifactId>
    <version>2.3.7</version>
</dependency>
----
