[[jakarta-ee]]
= Jakarta EE Specification Dependencies Mapping

This section details all dependencies linked to Jakarta EE specifications.

[[annotation]]
=== `annotation`

[[jackson-module-jaxb-annotations]]
==== *jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.module.jackson-module-jaxb-annotations]]
==== *com.fasterxml.jackson.module.jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson module: old jaxb annotations (javax.xml.bind)</groupId>
    <artifactId>com.fasterxml.jackson.module.jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[annotation-framework]]
==== *annotation-framework*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>annotation-framework</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jcip-annotations-repackaged]]
==== *jcip-annotations-repackaged*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jcip-annotations-repackaged</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.common.annotation-framework]]
==== *fish.payara.server.internal.common.annotation-framework*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>glassfish java ee annotation framework</groupId>
    <artifactId>fish.payara.server.internal.common.annotation-framework</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jcip-annotations]]
==== *jcip-annotations*
**Version**: 1.0-1

[source,xml]
----
<dependency>
    <groupId>com.github.stephenc.jcip</groupId>
    <artifactId>jcip-annotations</artifactId>
    <version>1.0-1</version>
</dependency>
----
[[jackson-annotations]]
==== *jackson-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.core.jackson-annotations]]
==== *com.fasterxml.jackson.core.jackson-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-annotations</groupId>
    <artifactId>com.fasterxml.jackson.core.jackson-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jakarta.annotation-api]]
==== *jakarta.annotation-api*
**Version**: 1.3.5

[source,xml]
----
<dependency>
    <groupId>jakarta.annotation</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>1.3.5</version>
</dependency>
----
[[jakarta.annotation-api]]
==== *jakarta.annotation-api*
**Version**: 1.3.5

[source,xml]
----
<dependency>
    <groupId>jakarta.annotation</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>1.3.5</version>
</dependency>
----
[[jakarta.annotation-api]]
==== *jakarta.annotation-api*
**Version**: 1.3.5

[source,xml]
----
<dependency>
    <groupId>jakarta annotations api</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>1.3.5</version>
</dependency>
----
[[jakarta.annotation-api]]
==== *jakarta.annotation-api*
**Version**: 1.3.5

[source,xml]
----
<dependency>
    <groupId>jakarta annotations api</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>1.3.5</version>
</dependency>
----
[[authentication]]
=== `authentication`

[[authorization]]
=== `authorization`

[[batch]]
=== `batch`

[[glassfish-batch-connector]]
==== *glassfish-batch-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>glassfish-batch-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.batch.glassfish-batch-connector]]
==== *fish.payara.server.internal.batch.glassfish-batch-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>batch connector for glassfish</groupId>
    <artifactId>fish.payara.server.internal.batch.glassfish-batch-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[glassfish-batch-commands]]
==== *glassfish-batch-commands*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>glassfish-batch-commands</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.batch.glassfish-batch-commands]]
==== *fish.payara.server.internal.batch.glassfish-batch-commands*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>batch commands for glassfish</groupId>
    <artifactId>fish.payara.server.internal.batch.glassfish-batch-commands</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[payara-jbatch]]
==== *payara-jbatch*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>payara-jbatch</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[payara-jbatch]]
==== *payara-jbatch*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>payara-jbatch</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.batch.payara-jbatch]]
==== *fish.payara.server.internal.batch.payara-jbatch*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ibm jbatch combined</groupId>
    <artifactId>fish.payara.server.internal.batch.payara-jbatch</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.batch.payara-jbatch]]
==== *fish.payara.server.internal.batch.payara-jbatch*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ibm jbatch combined</groupId>
    <artifactId>fish.payara.server.internal.batch.payara-jbatch</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.batch-api]]
==== *jakarta.batch-api*
**Version**: 1.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.batch</groupId>
    <artifactId>jakarta.batch-api</artifactId>
    <version>1.0.2</version>
</dependency>
----
[[jakarta.batch-api]]
==== *jakarta.batch-api*
**Version**: 1.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.batch</groupId>
    <artifactId>jakarta.batch-api</artifactId>
    <version>1.0.2</version>
</dependency>
----
[[validation]]
=== `validation`

[[hibernate-validator]]
==== *hibernate-validator*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[org.hibernate.validator]]
==== *org.hibernate.validator*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>hibernate validator engine</groupId>
    <artifactId>org.hibernate.validator</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[hibernate-validator-cdi]]
==== *hibernate-validator-cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[org.hibernate.validator.cdi]]
==== *org.hibernate.validator.cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>hibernate validator portable extension</groupId>
    <artifactId>org.hibernate.validator.cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[jersey-bean-validation]]
==== *jersey-bean-validation*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-bean-validation</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-bean-validation]]
==== *jersey-bean-validation*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-bean-validation</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-bean-validation]]
==== *org.glassfish.jersey.ext.jersey-bean-validation*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-bean-validation</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-bean-validation</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-bean-validation]]
==== *org.glassfish.jersey.ext.jersey-bean-validation*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-bean-validation</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-bean-validation</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jakarta.validation-api]]
==== *jakarta.validation-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.validation</groupId>
    <artifactId>jakarta.validation-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[jakarta.validation.jakarta.validation-api]]
==== *jakarta.validation.jakarta.validation-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta bean validation api</groupId>
    <artifactId>jakarta.validation.jakarta.validation-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[concurrency]]
=== `concurrency`

[[concurrent-impl]]
==== *concurrent-impl*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-impl</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[concurrent-impl]]
==== *concurrent-impl*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-impl</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.concurrent.impl]]
==== *fish.payara.server.internal.concurrent.impl*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>concurrent implementation module</groupId>
    <artifactId>fish.payara.server.internal.concurrent.impl</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.concurrent.impl]]
==== *fish.payara.server.internal.concurrent.impl*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>concurrent implementation module</groupId>
    <artifactId>fish.payara.server.internal.concurrent.impl</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[concurrent-connector]]
==== *concurrent-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.concurrent.connector]]
==== *fish.payara.server.internal.concurrent.connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>concurrent connector module</groupId>
    <artifactId>fish.payara.server.internal.concurrent.connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[javax.enterprise.concurrent]]
==== *javax.enterprise.concurrent*
**Version**: 1.1.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>javax.enterprise.concurrent</artifactId>
    <version>1.1.payara-p1</version>
</dependency>
----
[[jakarta.enterprise.concurrent-api]]
==== *jakarta.enterprise.concurrent-api*
**Version**: 1.1.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise.concurrent</groupId>
    <artifactId>jakarta.enterprise.concurrent-api</artifactId>
    <version>1.1.2</version>
</dependency>
----
[[jakarta.enterprise.concurrent-api]]
==== *jakarta.enterprise.concurrent-api*
**Version**: 1.1.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise.concurrent</groupId>
    <artifactId>jakarta.enterprise.concurrent-api</artifactId>
    <version>1.1.2</version>
</dependency>
----
[[console-concurrent-plugin]]
==== *console-concurrent-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-concurrent-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-concurrent-plugin]]
==== *fish.payara.server.internal.admingui.console-concurrent-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>admin console concurrent plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-concurrent-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[connectors]]
=== `connectors`

[[connectors-inbound-runtime]]
==== *connectors-inbound-runtime*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-inbound-runtime</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.connectors.inbound-runtime]]
==== *fish.payara.server.internal.connectors.inbound-runtime*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>connectors inbound support</groupId>
    <artifactId>fish.payara.server.internal.connectors.inbound-runtime</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[connectors-admin]]
==== *connectors-admin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-admin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.connectors.admin]]
==== *fish.payara.server.internal.connectors.admin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>connectors admin</groupId>
    <artifactId>fish.payara.server.internal.connectors.admin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[connectors-internal-api]]
==== *connectors-internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[connectors-internal-api]]
==== *connectors-internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.connectors.internal-api]]
==== *fish.payara.server.internal.connectors.internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>connectors private apis for glassfish containers</groupId>
    <artifactId>fish.payara.server.internal.connectors.internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.connectors.internal-api]]
==== *fish.payara.server.internal.connectors.internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>connectors private apis for glassfish containers</groupId>
    <artifactId>fish.payara.server.internal.connectors.internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[connectors-runtime]]
==== *connectors-runtime*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-runtime</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[connectors-runtime]]
==== *connectors-runtime*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-runtime</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.connectors.runtime]]
==== *fish.payara.server.internal.connectors.runtime*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>connectors runtime</groupId>
    <artifactId>fish.payara.server.internal.connectors.runtime</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.connectors.runtime]]
==== *fish.payara.server.internal.connectors.runtime*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>connectors runtime</groupId>
    <artifactId>fish.payara.server.internal.connectors.runtime</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[gf-connectors-connector]]
==== *gf-connectors-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>gf-connectors-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.connectors.gf-connectors-connector]]
==== *fish.payara.server.internal.connectors.gf-connectors-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>glassfish connectors connector</groupId>
    <artifactId>fish.payara.server.internal.connectors.gf-connectors-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.connectors.work-management]]
==== *fish.payara.server.internal.connectors.work-management*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>work management</groupId>
    <artifactId>fish.payara.server.internal.connectors.work-management</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[security-connectors-api]]
==== *security-connectors-api*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connectors-api</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[fish.payara.security.connectors.security-connectors-api]]
==== *fish.payara.security.connectors.security-connectors-api*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>payara security connnectors api</groupId>
    <artifactId>fish.payara.security.connectors.security-connectors-api</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[contextdependencyinjection]]
=== `contextdependencyinjection`

[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta cdi</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta cdi</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[payara-micro-cdi]]
==== *payara-micro-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-micro-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi]]
==== *fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>payara micro cdi</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jersey-cdi1x]]
==== *jersey-cdi1x*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[cdi-api-fragment]]
==== *cdi-api-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>cdi-api-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cdi-api-fragment]]
==== *cdi-api-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>cdi-api-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[gf-weld-connector]]
==== *gf-weld-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>gf-weld-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.gf-weld-connector]]
==== *fish.payara.server.internal.web.gf-weld-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>weld connector for glassfish</groupId>
    <artifactId>fish.payara.server.internal.web.gf-weld-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[tyrus-container-glassfish-cdi]]
==== *tyrus-container-glassfish-cdi*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-cdi</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.container-glassfish-cdi]]
==== *org.glassfish.tyrus.container-glassfish-cdi*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus cdi component provider</groupId>
    <artifactId>org.glassfish.tyrus.container-glassfish-cdi</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[hibernate-validator-cdi]]
==== *hibernate-validator-cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[org.hibernate.validator.cdi]]
==== *org.hibernate.validator.cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>hibernate validator portable extension</groupId>
    <artifactId>org.hibernate.validator.cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-transaction</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-servlet]]
==== *jersey-cdi1x-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-servlet</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[cdi-auth-roles]]
==== *cdi-auth-roles*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>cdi-auth-roles</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles]]
==== *fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi auth: roles</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cdieventbus-notifier-console-plugin]]
==== *cdieventbus-notifier-console-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>cdieventbus-notifier-console-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin]]
==== *fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi event bus notifier console plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[opentracing-cdi]]
==== *opentracing-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.opentracing-cdi]]
==== *fish.payara.server.internal.payara-appserver-modules.opentracing-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>opentracing cdi</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.opentracing-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[weld-integration-fragment]]
==== *weld-integration-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.weld-integration-fragment]]
==== *fish.payara.server.internal.web.weld-integration-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>weld integration fragment</groupId>
    <artifactId>fish.payara.server.internal.web.weld-integration-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[weld-integration]]
==== *weld-integration*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.weld-integration]]
==== *fish.payara.server.internal.web.weld-integration*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>weld integration for glassfish</groupId>
    <artifactId>fish.payara.server.internal.web.weld-integration</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[notification-cdi-eventbus-core]]
==== *notification-cdi-eventbus-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-cdi-eventbus-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core]]
==== *fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi eventbus notification implementation</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[weld-ejb]]
==== *weld-ejb*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-ejb</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-jsf]]
==== *weld-jsf*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-jta]]
==== *weld-jta*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jta</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-web]]
==== *weld-web*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-web</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-probe-core]]
==== *weld-probe-core*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.probe</groupId>
    <artifactId>weld-probe-core</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-api]]
==== *weld-api*
**Version**: 3.1.sp4

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-api</artifactId>
    <version>3.1.sp4</version>
</dependency>
----
[[weld-core-impl]]
==== *weld-core-impl*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-core-impl</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-osgi-bundle]]
==== *weld-osgi-bundle*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-osgi-bundle</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-spi]]
==== *weld-spi*
**Version**: 3.1.sp4

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-spi</artifactId>
    <version>3.1.sp4</version>
</dependency>
----
[[org.jboss.weld.osgi-bundle]]
==== *org.jboss.weld.osgi-bundle*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>weld osgi bundle</groupId>
    <artifactId>org.jboss.weld.osgi-bundle</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[debugging]]
=== `debugging`

[[dependencyinjection]]
=== `dependencyinjection`

[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[asadmin-audit]]
==== *asadmin-audit*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>asadmin-audit</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta cdi</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.asadmin-audit]]
==== *fish.payara.server.internal.payara-modules.asadmin-audit*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>payara asadmin auditor</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.asadmin-audit</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jersey-media-multipart]]
==== *jersey-media-multipart*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-multipart</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-multipart</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-media-json-jackson]]
==== *jersey-media-json-jackson*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-jackson</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-jackson</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[console-payara-branding-plugin]]
==== *console-payara-branding-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-payara-branding-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-payara-branding-plugin]]
==== *fish.payara.server.internal.admingui.console-payara-branding-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>admin console payara theme plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-payara-branding-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[gf-jms-injection]]
==== *gf-jms-injection*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-injection</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.jms.gf-jms-injection]]
==== *fish.payara.server.internal.jms.gf-jms-injection*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jms injection module for runtime</groupId>
    <artifactId>fish.payara.server.internal.jms.gf-jms-injection</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jersey-media-jaxb]]
==== *jersey-media-jaxb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-jaxb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-jaxb</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[payara-micro-cdi]]
==== *payara-micro-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-micro-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi]]
==== *fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>payara micro cdi</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.payara-micro-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[org.glassfish.jersey.inject.jersey-hk2]]
==== *org.glassfish.jersey.inject.jersey-hk2*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-inject-hk2</groupId>
    <artifactId>org.glassfish.jersey.inject.jersey-hk2</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-cdi1x]]
==== *jersey-cdi1x*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-media-json-binding]]
==== *jersey-media-json-binding*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-binding</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[cdi-api-fragment]]
==== *cdi-api-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>cdi-api-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.inject]]
==== *jakarta.inject*
**Version**: 2.6.1.payara-p8

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2.external</groupId>
    <artifactId>jakarta.inject</artifactId>
    <version>2.6.1.payara-p8</version>
</dependency>
----
[[org.glassfish.hk2.external.jakarta.inject]]
==== *org.glassfish.hk2.external.jakarta.inject*
**Version**: 2.6.1.payara-p8

[source,xml]
----
<dependency>
    <groupId>javax.inject:1 as osgi bundle</groupId>
    <artifactId>org.glassfish.hk2.external.jakarta.inject</artifactId>
    <version>2.6.1.payara-p8</version>
</dependency>
----
[[jersey-media-moxy]]
==== *jersey-media-moxy*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-moxy</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-moxy</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-media-json-processing]]
==== *jersey-media-json-processing*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-processing</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[gf-weld-connector]]
==== *gf-weld-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>gf-weld-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.gf-weld-connector]]
==== *fish.payara.server.internal.web.gf-weld-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>weld connector for glassfish</groupId>
    <artifactId>fish.payara.server.internal.web.gf-weld-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[tyrus-container-glassfish-cdi]]
==== *tyrus-container-glassfish-cdi*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-cdi</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.container-glassfish-cdi]]
==== *org.glassfish.tyrus.container-glassfish-cdi*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus cdi component provider</groupId>
    <artifactId>org.glassfish.tyrus.container-glassfish-cdi</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[hibernate-validator-cdi]]
==== *hibernate-validator-cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[org.hibernate.validator.cdi]]
==== *org.hibernate.validator.cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>hibernate validator portable extension</groupId>
    <artifactId>org.hibernate.validator.cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-transaction</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-servlet]]
==== *jersey-cdi1x-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-sse]]
==== *jersey-media-sse*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-sse</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-sse</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-servlet</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[cdi-auth-roles]]
==== *cdi-auth-roles*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>cdi-auth-roles</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles]]
==== *fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi auth: roles</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.cdi-auth-roles</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cdieventbus-notifier-console-plugin]]
==== *cdieventbus-notifier-console-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>cdieventbus-notifier-console-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin]]
==== *fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi event bus notifier console plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.cdieventbus-notifier-console-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[hazelcast-eclipselink-coordination]]
==== *hazelcast-eclipselink-coordination*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>hazelcast-eclipselink-coordination</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.hazelcast-eclipselink-coordination]]
==== *fish.payara.server.internal.payara-appserver-modules.hazelcast-eclipselink-coordination*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>hz eclipselink coordination</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.hazelcast-eclipselink-coordination</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[opentracing-cdi]]
==== *opentracing-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.opentracing-cdi]]
==== *fish.payara.server.internal.payara-appserver-modules.opentracing-cdi*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>opentracing cdi</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.opentracing-cdi</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[weld-integration-fragment]]
==== *weld-integration-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.weld-integration-fragment]]
==== *fish.payara.server.internal.web.weld-integration-fragment*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>weld integration fragment</groupId>
    <artifactId>fish.payara.server.internal.web.weld-integration-fragment</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[weld-integration]]
==== *weld-integration*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.weld-integration]]
==== *fish.payara.server.internal.web.weld-integration*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>weld integration for glassfish</groupId>
    <artifactId>fish.payara.server.internal.web.weld-integration</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[notification-cdi-eventbus-core]]
==== *notification-cdi-eventbus-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-cdi-eventbus-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core]]
==== *fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>cdi eventbus notification implementation</groupId>
    <artifactId>fish.payara.server.internal.payara-modules.notification-cdi-eventbus-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[weld-ejb]]
==== *weld-ejb*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-ejb</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-jsf]]
==== *weld-jsf*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-jta]]
==== *weld-jta*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jta</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-web]]
==== *weld-web*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-web</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-probe-core]]
==== *weld-probe-core*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.probe</groupId>
    <artifactId>weld-probe-core</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-api]]
==== *weld-api*
**Version**: 3.1.sp4

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-api</artifactId>
    <version>3.1.sp4</version>
</dependency>
----
[[weld-core-impl]]
==== *weld-core-impl*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-core-impl</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-osgi-bundle]]
==== *weld-osgi-bundle*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-osgi-bundle</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-spi]]
==== *weld-spi*
**Version**: 3.1.sp4

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-spi</artifactId>
    <version>3.1.sp4</version>
</dependency>
----
[[org.jboss.weld.osgi-bundle]]
==== *org.jboss.weld.osgi-bundle*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>weld osgi bundle</groupId>
    <artifactId>org.jboss.weld.osgi-bundle</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[deployment]]
=== `deployment`

[[deployment-javaee-full]]
==== *deployment-javaee-full*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-javaee-full</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.deployment.javaee-full]]
==== *fish.payara.server.internal.deployment.javaee-full*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>deployment related javaee full profile classes</groupId>
    <artifactId>fish.payara.server.internal.deployment.javaee-full</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[deployment-javaee-core]]
==== *deployment-javaee-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-javaee-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.deployment.javaee-core]]
==== *fish.payara.server.internal.deployment.javaee-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>deployment related javaee core classes</groupId>
    <artifactId>fish.payara.server.internal.deployment.javaee-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[deployment-admin]]
==== *deployment-admin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-admin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.deployment.admin]]
==== *fish.payara.server.internal.deployment.admin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>deployment related admin classes</groupId>
    <artifactId>fish.payara.server.internal.deployment.admin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[deployment-client]]
==== *deployment-client*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-client</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.deployment.deployment-client]]
==== *fish.payara.server.internal.deployment.deployment-client*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>deployment client classes and interfaces</groupId>
    <artifactId>fish.payara.server.internal.deployment.deployment-client</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[deployment-common]]
==== *deployment-common*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-common</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.deployment.common]]
==== *fish.payara.server.internal.deployment.common*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>deployment related common classes</groupId>
    <artifactId>fish.payara.server.internal.deployment.common</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.deployment.dol]]
==== *fish.payara.server.internal.deployment.dol*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>deployment object library</groupId>
    <artifactId>fish.payara.server.internal.deployment.dol</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[deployment-autodeploy]]
==== *deployment-autodeploy*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-autodeploy</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.deployment.autodeploy]]
==== *fish.payara.server.internal.deployment.autodeploy*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>autodeploy classes</groupId>
    <artifactId>fish.payara.server.internal.deployment.autodeploy</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[eeplatform]]
=== `eeplatform`

[[enterprisebeans]]
=== `enterprisebeans`

[[ejb-full-container]]
==== *ejb-full-container*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-full-container</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.ejb.ejb-full-container]]
==== *fish.payara.server.internal.ejb.ejb-full-container*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>full ejb container add-ons</groupId>
    <artifactId>fish.payara.server.internal.ejb.ejb-full-container</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-utility]]
==== *cmp-utility*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-utility</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.utility]]
==== *fish.payara.server.internal.persistence.cmp.utility*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>utility module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.utility</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-generator-database]]
==== *cmp-generator-database*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-generator-database</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.generator-database]]
==== *fish.payara.server.internal.persistence.cmp.generator-database*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>database generator module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.generator-database</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-support-sqlstore]]
==== *cmp-support-sqlstore*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-sqlstore</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.support-sqlstore]]
==== *fish.payara.server.internal.persistence.cmp.support-sqlstore*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>support-sqlstore module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.support-sqlstore</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-model]]
==== *cmp-model*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-model</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.model]]
==== *fish.payara.server.internal.persistence.cmp.model*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>model module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.model</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[entitybean-container]]
==== *entitybean-container*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>entitybean-container</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.entitybean-container]]
==== *fish.payara.server.internal.persistence.entitybean-container*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>entity bean container</groupId>
    <artifactId>fish.payara.server.internal.persistence.entitybean-container</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[tyrus-container-glassfish-ejb]]
==== *tyrus-container-glassfish-ejb*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-ejb</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.container-glassfish-ejb]]
==== *org.glassfish.tyrus.container-glassfish-ejb*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus ejb component provider</groupId>
    <artifactId>org.glassfish.tyrus.container-glassfish-ejb</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[console-ejb-plugin]]
==== *console-ejb-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-ejb-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-ejb-plugin]]
==== *fish.payara.server.internal.admingui.console-ejb-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>admin console ejb container plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-ejb-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[ejb-client]]
==== *ejb-client*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-client</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.ejb.ejb-client]]
==== *fish.payara.server.internal.ejb.ejb-client*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>glassfish core ejb client</groupId>
    <artifactId>fish.payara.server.internal.ejb.ejb-client</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-internal-api]]
==== *cmp-internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.internal-api]]
==== *fish.payara.server.internal.persistence.cmp.internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>internal-api module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[ejb-http-admin]]
==== *ejb-http-admin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-http-admin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.ejb.http-admin]]
==== *fish.payara.server.internal.ejb.http-admin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ejb - http admin</groupId>
    <artifactId>fish.payara.server.internal.ejb.http-admin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jersey-gf-ejb]]
==== *jersey-gf-ejb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers.glassfish</groupId>
    <artifactId>jersey-gf-ejb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.glassfish.]]
==== *org.glassfish.jersey.containers.glassfish.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-gf-ejb</groupId>
    <artifactId>org.glassfish.jersey.containers.glassfish.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[ejb-opentracing]]
==== *ejb-opentracing*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-opentracing</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.ejb.opentracing]]
==== *fish.payara.server.internal.ejb.opentracing*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ejb-opentracing</groupId>
    <artifactId>fish.payara.server.internal.ejb.opentracing</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[hazelcast-ejb-timer]]
==== *hazelcast-ejb-timer*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>hazelcast-ejb-timer</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.hazelcast-ejb-timer]]
==== *fish.payara.server.internal.payara-appserver-modules.hazelcast-ejb-timer*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>hz ejb timer</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.hazelcast-ejb-timer</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-support-ejb]]
==== *cmp-support-ejb*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-ejb</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-support-ejb]]
==== *cmp-support-ejb*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-ejb</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.support-ejb]]
==== *fish.payara.server.internal.persistence.cmp.support-ejb*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>support ejb module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.support-ejb</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.support-ejb]]
==== *fish.payara.server.internal.persistence.cmp.support-ejb*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>support ejb module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.support-ejb</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.ejb-api]]
==== *jakarta.ejb-api*
**Version**: 3.2.6

[source,xml]
----
<dependency>
    <groupId>jakarta.ejb</groupId>
    <artifactId>jakarta.ejb-api</artifactId>
    <version>3.2.6</version>
</dependency>
----
[[jakarta.ejb-api]]
==== *jakarta.ejb-api*
**Version**: 3.2.6

[source,xml]
----
<dependency>
    <groupId>jakarta.ejb</groupId>
    <artifactId>jakarta.ejb-api</artifactId>
    <version>3.2.6</version>
</dependency>
----
[[jakarta.ejb-api]]
==== *jakarta.ejb-api*
**Version**: 3.2.6

[source,xml]
----
<dependency>
    <groupId>jakarta enterprise beans</groupId>
    <artifactId>jakarta.ejb-api</artifactId>
    <version>3.2.6</version>
</dependency>
----
[[jakarta.ejb-api]]
==== *jakarta.ejb-api*
**Version**: 3.2.6

[source,xml]
----
<dependency>
    <groupId>jakarta enterprise beans</groupId>
    <artifactId>jakarta.ejb-api</artifactId>
    <version>3.2.6</version>
</dependency>
----
[[gf-ejb-connector]]
==== *gf-ejb-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>gf-ejb-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.ejb.gf-ejb-connector]]
==== *fish.payara.server.internal.ejb.gf-ejb-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ejb container connector for glassfish</groupId>
    <artifactId>fish.payara.server.internal.ejb.gf-ejb-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[ejb.security]]
==== *ejb.security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>ejb.security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.ejb.security]]
==== *fish.payara.server.internal.security.ejb.security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ejb security integration</groupId>
    <artifactId>fish.payara.server.internal.security.ejb.security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[console-ejb-lite-plugin]]
==== *console-ejb-lite-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-ejb-lite-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-ejb-lite-plugin]]
==== *fish.payara.server.internal.admingui.console-ejb-lite-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>admin console ejb local (lite) plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-ejb-lite-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[ejb-internal-api]]
==== *ejb-internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.ejb.internal-api]]
==== *fish.payara.server.internal.ejb.internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ejb container internal api</groupId>
    <artifactId>fish.payara.server.internal.ejb.internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-enhancer]]
==== *cmp-enhancer*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-enhancer</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.enhancer]]
==== *fish.payara.server.internal.persistence.cmp.enhancer*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>enhancer module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.enhancer</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-ejb-mapping]]
==== *cmp-ejb-mapping*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-ejb-mapping</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-ejb-mapping]]
==== *cmp-ejb-mapping*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-ejb-mapping</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.ejb-mapping]]
==== *fish.payara.server.internal.persistence.cmp.ejb-mapping*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ejb-mapping module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.ejb-mapping</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.ejb-mapping]]
==== *fish.payara.server.internal.persistence.cmp.ejb-mapping*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ejb-mapping module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.ejb-mapping</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[ejb-container]]
==== *ejb-container*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-container</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.ejb.ejb-container]]
==== *fish.payara.server.internal.ejb.ejb-container*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>glassfish core ejb container implementation</groupId>
    <artifactId>fish.payara.server.internal.ejb.ejb-container</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[weld-ejb]]
==== *weld-ejb*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-ejb</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[expressionlanguage]]
=== `expressionlanguage`

[[jakarta.el]]
==== *jakarta.el*
**Version**: 3.0.4.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jakarta.el</artifactId>
    <version>3.0.4.payara-p1</version>
</dependency>
----
[[com.sun.el.javax.el]]
==== *com.sun.el.javax.el*
**Version**: 3.0.4.payara-p1

[source,xml]
----
<dependency>
    <groupId>jakarta expression language 3.0</groupId>
    <artifactId>com.sun.el.javax.el</artifactId>
    <version>3.0.4.payara-p1</version>
</dependency>
----
[[interceptors]]
=== `interceptors`

[[jsonbinding]]
=== `jsonbinding`

[[jersey-media-json-binding]]
==== *jersey-media-json-binding*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-json-binding]]
==== *jersey-media-json-binding*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-binding</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-binding</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jsonprocessing]]
=== `jsonprocessing`

[[jackson-dataformat-xml]]
==== *jackson-dataformat-xml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.dataformat.jackson-dataformat-xml]]
==== *com.fasterxml.jackson.dataformat.jackson-dataformat-xml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-dataformat-xml</groupId>
    <artifactId>com.fasterxml.jackson.dataformat.jackson-dataformat-xml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-module-jaxb-annotations]]
==== *jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.module.jackson-module-jaxb-annotations]]
==== *com.fasterxml.jackson.module.jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson module: old jaxb annotations (javax.xml.bind)</groupId>
    <artifactId>com.fasterxml.jackson.module.jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jersey-media-json-jackson]]
==== *jersey-media-json-jackson*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-jackson</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-jackson</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jackson-databind]]
==== *jackson-databind*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.core.]]
==== *com.fasterxml.jackson.core.*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-databind</groupId>
    <artifactId>com.fasterxml.jackson.core.</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jersey-media-json-processing]]
==== *jersey-media-json-processing*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jsonp-jaxrs]]
==== *jsonp-jaxrs*
**Version**: 1.1.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jsonp-jaxrs</artifactId>
    <version>1.1.6</version>
</dependency>
----
[[org.glassfish.jsonp-jaxrs]]
==== *org.glassfish.jsonp-jaxrs*
**Version**: 1.1.5

[source,xml]
----
<dependency>
    <groupId>jakarta json processing media for jakarta restful web services</groupId>
    <artifactId>org.glassfish.jsonp-jaxrs</artifactId>
    <version>1.1.5</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-processing</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jackson-annotations]]
==== *jackson-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.core.jackson-annotations]]
==== *com.fasterxml.jackson.core.jackson-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-annotations</groupId>
    <artifactId>com.fasterxml.jackson.core.jackson-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-core]]
==== *jackson-core*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.core.jackson-core]]
==== *com.fasterxml.jackson.core.jackson-core*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-core</groupId>
    <artifactId>com.fasterxml.jackson.core.jackson-core</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-dataformat-yaml]]
==== *jackson-dataformat-yaml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-yaml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.dataformat.jackson-dataformat-yaml]]
==== *com.fasterxml.jackson.dataformat.jackson-dataformat-yaml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-dataformat-yaml</groupId>
    <artifactId>com.fasterxml.jackson.dataformat.jackson-dataformat-yaml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-core]]
==== *jackson-core*
**Version**: 2.12.1

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.12.1</version>
</dependency>
----
[[mail]]
=== `mail`

[[javamail-runtime]]
==== *javamail-runtime*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>javamail-runtime</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.resources.javamail-runtime]]
==== *fish.payara.server.internal.resources.javamail-runtime*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>glassfish javamail runtime</groupId>
    <artifactId>fish.payara.server.internal.resources.javamail-runtime</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.mail]]
==== *jakarta.mail*
**Version**: 1.6.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>com.sun.mail</groupId>
    <artifactId>jakarta.mail</artifactId>
    <version>1.6.7.payara-p1</version>
</dependency>
----
[[com.sun.mail.jakarta.mail]]
==== *com.sun.mail.jakarta.mail*
**Version**: 1.6.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>jakarta mail api</groupId>
    <artifactId>com.sun.mail.jakarta.mail</artifactId>
    <version>1.6.7.payara-p1</version>
</dependency>
----
[[javamail-connector]]
==== *javamail-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>javamail-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.resources.javamail-connector]]
==== *fish.payara.server.internal.resources.javamail-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>javamail connector</groupId>
    <artifactId>fish.payara.server.internal.resources.javamail-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[managedbeans]]
=== `managedbeans`

[[jsf-connector]]
==== *jsf-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jsf-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.jsf-connector]]
==== *fish.payara.server.internal.web.jsf-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jsf implementation connector module</groupId>
    <artifactId>fish.payara.server.internal.web.jsf-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jsft]]
==== *jsft*
**Version**: 2.1.4

[source,xml]
----
<dependency>
    <groupId>com.sun.jsftemplating</groupId>
    <artifactId>jsft</artifactId>
    <version>2.1.4</version>
</dependency>
----
[[jsftemplating]]
==== *jsftemplating*
**Version**: 2.1.4

[source,xml]
----
<dependency>
    <groupId>com.sun.jsftemplating</groupId>
    <artifactId>jsftemplating</artifactId>
    <version>2.1.4</version>
</dependency>
----
[[weld-jsf]]
==== *weld-jsf*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[management]]
=== `management`

[[jmx-monitoring-plugin]]
==== *jmx-monitoring-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>jmx-monitoring-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.admingui.jmx-monitoring-plugin]]
==== *fish.payara.server.internal.admingui.jmx-monitoring-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jmx monitoring plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.jmx-monitoring-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jmx-monitoring]]
==== *jmx-monitoring*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jmx-monitoring</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.jmx-monitoring]]
==== *fish.payara.server.internal.payara-appserver-modules.jmx-monitoring*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jmx monitoring</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.jmx-monitoring</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.management.j2ee-api]]
==== *jakarta.management.j2ee-api*
**Version**: 1.1.4

[source,xml]
----
<dependency>
    <groupId>jakarta.management.j2ee</groupId>
    <artifactId>jakarta.management.j2ee-api</artifactId>
    <version>1.1.4</version>
</dependency>
----
[[javax.management.j2ee-api]]
==== *javax.management.j2ee-api*
**Version**: 1.1.4

[source,xml]
----
<dependency>
    <groupId>javax.management.j2ee api</groupId>
    <artifactId>javax.management.j2ee-api</artifactId>
    <version>1.1.4</version>
</dependency>
----
[[work-management]]
==== *work-management*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>work-management</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.connectors.work-management]]
==== *fish.payara.server.internal.connectors.work-management*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>work management</groupId>
    <artifactId>fish.payara.server.internal.connectors.work-management</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[management-api]]
==== *management-api*
**Version**: 3.2.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.external</groupId>
    <artifactId>management-api</artifactId>
    <version>3.2.3.payara-p1</version>
</dependency>
----
[[management-api]]
==== *management-api*
**Version**: 3.2.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.external</groupId>
    <artifactId>management-api</artifactId>
    <version>3.2.3.payara-p1</version>
</dependency>
----
[[org.glassfish.external.]]
==== *org.glassfish.external.*
**Version**: 3.2.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>management-api</groupId>
    <artifactId>org.glassfish.external.</artifactId>
    <version>3.2.3.payara-p1</version>
</dependency>
----
[[org.glassfish.external.]]
==== *org.glassfish.external.*
**Version**: 3.2.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>management-api</groupId>
    <artifactId>org.glassfish.external.</artifactId>
    <version>3.2.3.payara-p1</version>
</dependency>
----
[[jmxremote_optional-repackaged]]
==== *jmxremote_optional-repackaged*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jmxremote_optional-repackaged</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.packager.jmxremote_optional-repackaged]]
==== *fish.payara.server.internal.packager.jmxremote_optional-repackaged*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jmxremote_optional repackaged as a module</groupId>
    <artifactId>fish.payara.server.internal.packager.jmxremote_optional-repackaged</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[messaging]]
=== `messaging`

[[jms-handlers]]
==== *jms-handlers*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-handlers</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.jms.handlers]]
==== *fish.payara.server.internal.jms.handlers*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jms annotation handlers</groupId>
    <artifactId>fish.payara.server.internal.jms.handlers</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[gf-jms-connector]]
==== *gf-jms-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.jms.gf-jms-connector]]
==== *fish.payara.server.internal.jms.gf-jms-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jms connector module for runtime</groupId>
    <artifactId>fish.payara.server.internal.jms.gf-jms-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[gf-jms-injection]]
==== *gf-jms-injection*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-injection</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.jms.gf-jms-injection]]
==== *fish.payara.server.internal.jms.gf-jms-injection*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jms injection module for runtime</groupId>
    <artifactId>fish.payara.server.internal.jms.gf-jms-injection</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[console-jms-plugin]]
==== *console-jms-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jms-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.admingui.console-jms-plugin]]
==== *fish.payara.server.internal.admingui.console-jms-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>admin console jms plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.console-jms-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.jms-api]]
==== *jakarta.jms-api*
**Version**: 2.0.3

[source,xml]
----
<dependency>
    <groupId>jakarta.jms</groupId>
    <artifactId>jakarta.jms-api</artifactId>
    <version>2.0.3</version>
</dependency>
----
[[jakarta.jms-api]]
==== *jakarta.jms-api*
**Version**: 2.0.3

[source,xml]
----
<dependency>
    <groupId>jakarta.jms</groupId>
    <artifactId>jakarta.jms-api</artifactId>
    <version>2.0.3</version>
</dependency>
----
[[jakarta.jms-api]]
==== *jakarta.jms-api*
**Version**: 2.0.3

[source,xml]
----
<dependency>
    <groupId>jakarta messaging api</groupId>
    <artifactId>jakarta.jms-api</artifactId>
    <version>2.0.3</version>
</dependency>
----
[[jakarta.jms-api]]
==== *jakarta.jms-api*
**Version**: 2.0.3

[source,xml]
----
<dependency>
    <groupId>jakarta messaging api</groupId>
    <artifactId>jakarta.jms-api</artifactId>
    <version>2.0.3</version>
</dependency>
----
[[notification-jms-core]]
==== *notification-jms-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>notification-jms-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.notification-jms-core]]
==== *fish.payara.server.internal.payara-appserver-modules.notification-jms-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jms notification implementation</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.notification-jms-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jms-admin]]
==== *jms-admin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-admin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.jms.admin]]
==== *fish.payara.server.internal.jms.admin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jms admin</groupId>
    <artifactId>fish.payara.server.internal.jms.admin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jms-core]]
==== *jms-core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.jms.core]]
==== *fish.payara.server.internal.jms.core*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jms module</groupId>
    <artifactId>fish.payara.server.internal.jms.core</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jms-notifier-console-plugin]]
==== *jms-notifier-console-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>jms-notifier-console-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.admingui.jms-notifier-console-plugin]]
==== *fish.payara.server.internal.admingui.jms-notifier-console-plugin*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jms notifier console plugin</groupId>
    <artifactId>fish.payara.server.internal.admingui.jms-notifier-console-plugin</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[persistence]]
=== `persistence`

[[persistence-common]]
==== *persistence-common*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>persistence-common</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.common]]
==== *fish.payara.server.internal.persistence.common*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>common persistence code between jpa and cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.common</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[org.eclipse.persistence.moxy]]
==== *org.eclipse.persistence.moxy*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink moxy</groupId>
    <artifactId>org.eclipse.persistence.moxy</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[org.eclipse.persistence.jpa.modelgen]]
==== *org.eclipse.persistence.jpa.modelgen*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink jpa modelgen</groupId>
    <artifactId>org.eclipse.persistence.jpa.modelgen</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[org.eclipse.persistence.jpa.modelgen]]
==== *org.eclipse.persistence.jpa.modelgen*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink jpa modelgen</groupId>
    <artifactId>org.eclipse.persistence.jpa.modelgen</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[org.eclipse.persistence.asm]]
==== *org.eclipse.persistence.asm*
**Version**: 9.4.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.asm</artifactId>
    <version>9.4.0</version>
</dependency>
----
[[org.eclipse.persistence.asm]]
==== *org.eclipse.persistence.asm*
**Version**: 9.4.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.asm</artifactId>
    <version>9.4.0</version>
</dependency>
----
[[org.eclipse.persistence.asm]]
==== *org.eclipse.persistence.asm*
**Version**: 9.4.0

[source,xml]
----
<dependency>
    <groupId>eclipselink asm</groupId>
    <artifactId>org.eclipse.persistence.asm</artifactId>
    <version>9.4.0</version>
</dependency>
----
[[org.eclipse.persistence.asm]]
==== *org.eclipse.persistence.asm*
**Version**: 9.4.0

[source,xml]
----
<dependency>
    <groupId>eclipselink asm</groupId>
    <artifactId>org.eclipse.persistence.asm</artifactId>
    <version>9.4.0</version>
</dependency>
----
[[org.eclipse.persistence.jpa.jpql]]
==== *org.eclipse.persistence.jpa.jpql*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink hermes parser</groupId>
    <artifactId>org.eclipse.persistence.jpa.jpql</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[org.eclipse.persistence.jpa.jpql]]
==== *org.eclipse.persistence.jpa.jpql*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink hermes parser</groupId>
    <artifactId>org.eclipse.persistence.jpa.jpql</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[cmp-utility]]
==== *cmp-utility*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-utility</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.utility]]
==== *fish.payara.server.internal.persistence.cmp.utility*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>utility module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.utility</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.utility]]
==== *fish.payara.server.internal.persistence.cmp.utility*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>utility module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.utility</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-generator-database]]
==== *cmp-generator-database*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-generator-database</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.generator-database]]
==== *fish.payara.server.internal.persistence.cmp.generator-database*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>database generator module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.generator-database</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.generator-database]]
==== *fish.payara.server.internal.persistence.cmp.generator-database*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>database generator module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.generator-database</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-support-sqlstore]]
==== *cmp-support-sqlstore*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-sqlstore</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.support-sqlstore]]
==== *fish.payara.server.internal.persistence.cmp.support-sqlstore*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>support-sqlstore module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.support-sqlstore</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.support-sqlstore]]
==== *fish.payara.server.internal.persistence.cmp.support-sqlstore*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>support-sqlstore module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.support-sqlstore</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.persistence]]
==== *jakarta.persistence*
**Version**: 2.2.3

[source,xml]
----
<dependency>
    <groupId>jakarta persistence api 2.2</groupId>
    <artifactId>jakarta.persistence</artifactId>
    <version>2.2.3</version>
</dependency>
----
[[cmp-model]]
==== *cmp-model*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-model</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.model]]
==== *fish.payara.server.internal.persistence.cmp.model*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>model module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.model</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.model]]
==== *fish.payara.server.internal.persistence.cmp.model*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>model module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.model</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[gf-jpa-connector]]
==== *gf-jpa-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>gf-jpa-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.gf-jpa-connector]]
==== *fish.payara.server.internal.persistence.gf-jpa-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>connector for jpa runtime in glassfish</groupId>
    <artifactId>fish.payara.server.internal.persistence.gf-jpa-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.gf-jpa-connector]]
==== *fish.payara.server.internal.persistence.gf-jpa-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>connector for jpa runtime in glassfish</groupId>
    <artifactId>fish.payara.server.internal.persistence.gf-jpa-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.entitybean-container]]
==== *fish.payara.server.internal.persistence.entitybean-container*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>entity bean container</groupId>
    <artifactId>fish.payara.server.internal.persistence.entitybean-container</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[org.eclipse.persistence.antlr]]
==== *org.eclipse.persistence.antlr*
**Version**: 3.5.2.v201711011707

[source,xml]
----
<dependency>
    <groupId>eclipselink antlr</groupId>
    <artifactId>org.eclipse.persistence.antlr</artifactId>
    <version>3.5.2.v201711011707</version>
</dependency>
----
[[org.eclipse.persistence.core]]
==== *org.eclipse.persistence.core*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink core</groupId>
    <artifactId>org.eclipse.persistence.core</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[jpa-container]]
==== *jpa-container*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>jpa-container</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.jpa-container]]
==== *fish.payara.server.internal.persistence.jpa-container*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jpa container for glassfish</groupId>
    <artifactId>fish.payara.server.internal.persistence.jpa-container</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.jpa-container]]
==== *fish.payara.server.internal.persistence.jpa-container*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jpa container for glassfish</groupId>
    <artifactId>fish.payara.server.internal.persistence.jpa-container</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[org.eclipse.persistence.oracle]]
==== *org.eclipse.persistence.oracle*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink oracle extensions</groupId>
    <artifactId>org.eclipse.persistence.oracle</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[org.eclipse.persistence.jpa]]
==== *org.eclipse.persistence.jpa*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink jpa</groupId>
    <artifactId>org.eclipse.persistence.jpa</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[org.eclipse.persistence.jpa]]
==== *org.eclipse.persistence.jpa*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink jpa</groupId>
    <artifactId>org.eclipse.persistence.jpa</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[org.eclipse.persistence.dbws]]
==== *org.eclipse.persistence.dbws*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink dbws</groupId>
    <artifactId>org.eclipse.persistence.dbws</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[cmp-internal-api]]
==== *cmp-internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.internal-api]]
==== *fish.payara.server.internal.persistence.cmp.internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>internal-api module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.internal-api]]
==== *fish.payara.server.internal.persistence.cmp.internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>internal-api module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[osgi-jpa-extension]]
==== *osgi-jpa-extension*
**Version**: 1.0.4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.fighterfish</groupId>
    <artifactId>osgi-jpa-extension</artifactId>
    <version>1.0.4</version>
</dependency>
----
[[org.glassfish.fighterfish.osgi-jpa-extension]]
==== *org.glassfish.fighterfish.osgi-jpa-extension*
**Version**: 1.0.4

[source,xml]
----
<dependency>
    <groupId>support for jpa in java se mode usage from osgi bundles</groupId>
    <artifactId>org.glassfish.fighterfish.osgi-jpa-extension</artifactId>
    <version>1.0.4</version>
</dependency>
----
[[cmp-support-ejb]]
==== *cmp-support-ejb*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-ejb</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.support-ejb]]
==== *fish.payara.server.internal.persistence.cmp.support-ejb*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>support ejb module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.support-ejb</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.support-ejb]]
==== *fish.payara.server.internal.persistence.cmp.support-ejb*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>support ejb module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.support-ejb</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[hazelcast-eclipselink-coordination]]
==== *hazelcast-eclipselink-coordination*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>hazelcast-eclipselink-coordination</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.hazelcast-eclipselink-coordination]]
==== *fish.payara.server.internal.payara-appserver-modules.hazelcast-eclipselink-coordination*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>hz eclipselink coordination</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.hazelcast-eclipselink-coordination</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-enhancer]]
==== *cmp-enhancer*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-enhancer</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.enhancer]]
==== *fish.payara.server.internal.persistence.cmp.enhancer*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>enhancer module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.enhancer</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.enhancer]]
==== *fish.payara.server.internal.persistence.cmp.enhancer*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>enhancer module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.enhancer</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[cmp-ejb-mapping]]
==== *cmp-ejb-mapping*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-ejb-mapping</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.ejb-mapping]]
==== *fish.payara.server.internal.persistence.cmp.ejb-mapping*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ejb-mapping module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.ejb-mapping</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.persistence.cmp.ejb-mapping]]
==== *fish.payara.server.internal.persistence.cmp.ejb-mapping*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ejb-mapping module for cmp</groupId>
    <artifactId>fish.payara.server.internal.persistence.cmp.ejb-mapping</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[restfulwebservice]]
=== `restfulwebservice`

[[jersey-media-multipart]]
==== *jersey-media-multipart*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-multipart</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-multipart</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-media-json-jackson]]
==== *jersey-media-json-jackson*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-jackson</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-jackson</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-mvc]]
==== *jersey-mvc*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-mvc]]
==== *org.glassfish.jersey.ext.jersey-mvc*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-mvc</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-mvc</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-media-jaxb]]
==== *jersey-media-jaxb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-jaxb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-jaxb</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-mvc-connector]]
==== *jersey-mvc-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jersey-mvc-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.jersey-mvc-connector]]
==== *fish.payara.server.internal.web.jersey-mvc-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jersey mvc tld connector implementation module</groupId>
    <artifactId>fish.payara.server.internal.web.jersey-mvc-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jersey-hk2]]
==== *jersey-hk2*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.inject</groupId>
    <artifactId>jersey-hk2</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.inject.jersey-hk2]]
==== *org.glassfish.jersey.inject.jersey-hk2*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-inject-hk2</groupId>
    <artifactId>org.glassfish.jersey.inject.jersey-hk2</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-mvc-jsp]]
==== *jersey-mvc-jsp*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc-jsp</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-mvc-jsp]]
==== *org.glassfish.jersey.ext.jersey-mvc-jsp*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-mvc-jsp</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-mvc-jsp</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-client]]
==== *jersey-client*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-client</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.core.jersey-client]]
==== *org.glassfish.jersey.core.jersey-client*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-core-client</groupId>
    <artifactId>org.glassfish.jersey.core.jersey-client</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-cdi1x]]
==== *jersey-cdi1x*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-media-json-binding]]
==== *jersey-media-json-binding*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-binding</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jaxrs-client-tracing]]
==== *jaxrs-client-tracing*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jaxrs-client-tracing</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.jaxrs-client-tracing]]
==== *fish.payara.server.internal.payara-appserver-modules.jaxrs-client-tracing*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>payara jax-rs client tracing</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.jaxrs-client-tracing</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jersey-media-moxy]]
==== *jersey-media-moxy*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-moxy</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-moxy</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-mp-rest-client]]
==== *jersey-mp-rest-client*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.microprofile</groupId>
    <artifactId>jersey-mp-rest-client</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.microprofile.]]
==== *org.glassfish.jersey.ext.microprofile.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-mp-rest-client</groupId>
    <artifactId>org.glassfish.jersey.ext.microprofile.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-proxy-client]]
==== *jersey-proxy-client*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-proxy-client</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-proxy-client]]
==== *org.glassfish.jersey.ext.jersey-proxy-client*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-proxy-client</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-proxy-client</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-media-json-processing]]
==== *jersey-media-json-processing*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jsonp-jaxrs]]
==== *jsonp-jaxrs*
**Version**: 1.1.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jsonp-jaxrs</artifactId>
    <version>1.1.6</version>
</dependency>
----
[[org.glassfish.jsonp-jaxrs]]
==== *org.glassfish.jsonp-jaxrs*
**Version**: 1.1.5

[source,xml]
----
<dependency>
    <groupId>jakarta json processing media for jakarta restful web services</groupId>
    <artifactId>org.glassfish.jsonp-jaxrs</artifactId>
    <version>1.1.5</version>
</dependency>
----
[[jersey-common]]
==== *jersey-common*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-common</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.core.jersey-common]]
==== *org.glassfish.jersey.core.jersey-common*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-core-common</groupId>
    <artifactId>org.glassfish.jersey.core.jersey-common</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-json-processing</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-server]]
==== *jersey-server*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-server</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-gf-ejb]]
==== *jersey-gf-ejb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers.glassfish</groupId>
    <artifactId>jersey-gf-ejb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.glassfish.]]
==== *org.glassfish.jersey.containers.glassfish.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-gf-ejb</groupId>
    <artifactId>org.glassfish.jersey.containers.glassfish.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.core.jersey-server]]
==== *org.glassfish.jersey.core.jersey-server*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-core-server</groupId>
    <artifactId>org.glassfish.jersey.core.jersey-server</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-transaction</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-bean-validation]]
==== *jersey-bean-validation*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-bean-validation</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-bean-validation]]
==== *org.glassfish.jersey.ext.jersey-bean-validation*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-bean-validation</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-bean-validation</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-servlet]]
==== *jersey-cdi1x-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-sse]]
==== *jersey-media-sse*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-sse</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-sse</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-servlet</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-entity-filtering]]
==== *jersey-entity-filtering*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-entity-filtering</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-entity-filtering]]
==== *org.glassfish.jersey.ext.jersey-entity-filtering*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-entity-filtering</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-entity-filtering</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-container-servlet-core]]
==== *jersey-container-servlet-core*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet-core</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.]]
==== *org.glassfish.jersey.containers.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-container-servlet-core</groupId>
    <artifactId>org.glassfish.jersey.containers.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-container-servlet]]
==== *jersey-container-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.]]
==== *org.glassfish.jersey.containers.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-container-servlet</groupId>
    <artifactId>org.glassfish.jersey.containers.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-container-grizzly2-http]]
==== *jersey-container-grizzly2-http*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-grizzly2-http</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.]]
==== *org.glassfish.jersey.containers.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-container-grizzly2-http</groupId>
    <artifactId>org.glassfish.jersey.containers.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[security]]
=== `security`

[[jakarta.security.auth.message-api]]
==== *jakarta.security.auth.message-api*
**Version**: 1.1.3

[source,xml]
----
<dependency>
    <groupId>jakarta.security.auth.message</groupId>
    <artifactId>jakarta.security.auth.message-api</artifactId>
    <version>1.1.3</version>
</dependency>
----
[[javax.security.auth.message-api]]
==== *javax.security.auth.message-api*
**Version**: 1.1.3

[source,xml]
----
<dependency>
    <groupId>jakarta authentication</groupId>
    <artifactId>javax.security.auth.message-api</artifactId>
    <version>1.1.3</version>
</dependency>
----
[[fish.payara.server.internal.security.jacc.provider.file]]
==== *fish.payara.server.internal.security.jacc.provider.file*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>a pluggable file based jacc provider</groupId>
    <artifactId>fish.payara.server.internal.security.jacc.provider.file</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[appclient.security]]
==== *appclient.security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>appclient.security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.appclient.security]]
==== *fish.payara.server.internal.security.appclient.security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>appclient security integration</groupId>
    <artifactId>fish.payara.server.internal.security.appclient.security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[javax.security.enterprise]]
==== *javax.security.enterprise*
**Version**: 1.1-b01.payara-p5

[source,xml]
----
<dependency>
    <groupId>org.glassfish.soteria</groupId>
    <artifactId>javax.security.enterprise</artifactId>
    <version>1.1-b01.payara-p5</version>
</dependency>
----
[[org.glassfish.soteria.javax.security.enterprise]]
==== *org.glassfish.soteria.javax.security.enterprise*
**Version**: 1.0.99.b01

[source,xml]
----
<dependency>
    <groupId>soteria reference implementation</groupId>
    <artifactId>org.glassfish.soteria.javax.security.enterprise</artifactId>
    <version>1.0.99.b01</version>
</dependency>
----
[[jcip-annotations]]
==== *jcip-annotations*
**Version**: 1.0-1

[source,xml]
----
<dependency>
    <groupId>com.github.stephenc.jcip</groupId>
    <artifactId>jcip-annotations</artifactId>
    <version>1.0-1</version>
</dependency>
----
[[nimbus-jose-jwt]]
==== *nimbus-jose-jwt*
**Version**: 9.10.1

[source,xml]
----
<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>nimbus-jose-jwt</artifactId>
    <version>9.10.1</version>
</dependency>
----
[[security-connector-oidc-client]]
==== *security-connector-oidc-client*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connector-oidc-client</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[accessors-smart]]
==== *accessors-smart*
**Version**: 2.4.7

[source,xml]
----
<dependency>
    <groupId>net.minidev</groupId>
    <artifactId>accessors-smart</artifactId>
    <version>2.4.7</version>
</dependency>
----
[[json-smart]]
==== *json-smart*
**Version**: 2.4.7

[source,xml]
----
<dependency>
    <groupId>net.minidev</groupId>
    <artifactId>json-smart</artifactId>
    <version>2.4.7</version>
</dependency>
----
[[security-connector-oidc-client]]
==== *security-connector-oidc-client*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>security connector - openid connect client</groupId>
    <artifactId>security-connector-oidc-client</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[websecurity]]
==== *websecurity*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>websecurity</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.websecurity]]
==== *fish.payara.server.internal.security.websecurity*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>webtier security integration</groupId>
    <artifactId>fish.payara.server.internal.security.websecurity</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.security.enterprise-api]]
==== *jakarta.security.enterprise-api*
**Version**: 1.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.security.enterprise</groupId>
    <artifactId>jakarta.security.enterprise-api</artifactId>
    <version>1.0.2</version>
</dependency>
----
[[javax.security.enterprise-api]]
==== *javax.security.enterprise-api*
**Version**: 1.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta security</groupId>
    <artifactId>javax.security.enterprise-api</artifactId>
    <version>1.0.2</version>
</dependency>
----
[[security-connector-oauth2-client]]
==== *security-connector-oauth2-client*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connector-oauth2-client</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[security-connector-oauth2-client]]
==== *security-connector-oauth2-client*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>security connector - oauth2 client</groupId>
    <artifactId>security-connector-oauth2-client</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[security-ee]]
==== *security-ee*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security-ee</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.ee]]
==== *fish.payara.server.internal.security.ee*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>java ee security core classes</groupId>
    <artifactId>fish.payara.server.internal.security.ee</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.ssl-impl]]
==== *fish.payara.server.internal.security.ssl-impl*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>glassfish ssl implementation module</groupId>
    <artifactId>fish.payara.server.internal.security.ssl-impl</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[security]]
==== *security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security]]
==== *fish.payara.server.internal.security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>security core classes</groupId>
    <artifactId>fish.payara.server.internal.security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.security.jacc-api]]
==== *jakarta.security.jacc-api*
**Version**: 1.6.1

[source,xml]
----
<dependency>
    <groupId>jakarta.security.jacc</groupId>
    <artifactId>jakarta.security.jacc-api</artifactId>
    <version>1.6.1</version>
</dependency>
----
[[javax.security.jacc-api]]
==== *javax.security.jacc-api*
**Version**: 1.6.1

[source,xml]
----
<dependency>
    <groupId>jacc api</groupId>
    <artifactId>javax.security.jacc-api</artifactId>
    <version>1.6.1</version>
</dependency>
----
[[security-services]]
==== *security-services*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security-services</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.services]]
==== *fish.payara.server.internal.security.services*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>security services and spi</groupId>
    <artifactId>fish.payara.server.internal.security.services</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.realm-stores]]
==== *fish.payara.server.internal.security.realm-stores*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>realm identity stores</groupId>
    <artifactId>fish.payara.server.internal.security.realm-stores</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.jaspic.provider.framework]]
==== *fish.payara.server.internal.security.jaspic.provider.framework*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jaspic provider framework</groupId>
    <artifactId>fish.payara.server.internal.security.jaspic.provider.framework</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[webservices.security]]
==== *webservices.security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>webservices.security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.webservices.security]]
==== *fish.payara.server.internal.security.webservices.security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>webservices security and jsr 196 implementation</groupId>
    <artifactId>fish.payara.server.internal.security.webservices.security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[security-connectors-api]]
==== *security-connectors-api*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connectors-api</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[fish.payara.security.connectors.security-connectors-api]]
==== *fish.payara.security.connectors.security-connectors-api*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>payara security connnectors api</groupId>
    <artifactId>fish.payara.security.connectors.security-connectors-api</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[ejb.security]]
==== *ejb.security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>ejb.security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.ejb.security]]
==== *fish.payara.server.internal.security.ejb.security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>ejb security integration</groupId>
    <artifactId>fish.payara.server.internal.security.ejb.security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.jacc.provider.inmemory]]
==== *fish.payara.server.internal.security.jacc.provider.inmemory*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>a pluggable inmemory jacc provider</groupId>
    <artifactId>fish.payara.server.internal.security.jacc.provider.inmemory</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[serverfaces]]
=== `serverfaces`

[[jsf-connector]]
==== *jsf-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jsf-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.jsf-connector]]
==== *fish.payara.server.internal.web.jsf-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jsf implementation connector module</groupId>
    <artifactId>fish.payara.server.internal.web.jsf-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.faces]]
==== *jakarta.faces*
**Version**: 2.3.14.payara-p3

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jakarta.faces</artifactId>
    <version>2.3.14.payara-p3</version>
</dependency>
----
[[org.glassfish.jakarta.faces]]
==== *org.glassfish.jakarta.faces*
**Version**: 2.3.14.payara-p3

[source,xml]
----
<dependency>
    <groupId>mojarra jsf implementation 2.3.14.payara-p3</groupId>
    <artifactId>org.glassfish.jakarta.faces</artifactId>
    <version>2.3.14.payara-p3</version>
</dependency>
----
[[jsft]]
==== *jsft*
**Version**: 2.1.4

[source,xml]
----
<dependency>
    <groupId>com.sun.jsftemplating</groupId>
    <artifactId>jsft</artifactId>
    <version>2.1.4</version>
</dependency>
----
[[jsftemplating]]
==== *jsftemplating*
**Version**: 2.1.4

[source,xml]
----
<dependency>
    <groupId>com.sun.jsftemplating</groupId>
    <artifactId>jsftemplating</artifactId>
    <version>2.1.4</version>
</dependency>
----
[[weld-jsf]]
==== *weld-jsf*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[serverpages]]
=== `serverpages`

[[javax.servlet.jsp]]
==== *javax.servlet.jsp*
**Version**: 2.3.4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>javax.servlet.jsp</artifactId>
    <version>2.3.4</version>
</dependency>
----
[[org.glassfish.web.javax.servlet.jsp]]
==== *org.glassfish.web.javax.servlet.jsp*
**Version**: 2.3.4

[source,xml]
----
<dependency>
    <groupId>jsp implementation</groupId>
    <artifactId>org.glassfish.web.javax.servlet.jsp</artifactId>
    <version>2.3.4</version>
</dependency>
----
[[jersey-mvc-jsp]]
==== *jersey-mvc-jsp*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc-jsp</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.jersey-mvc-jsp]]
==== *org.glassfish.jersey.ext.jersey-mvc-jsp*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-mvc-jsp</groupId>
    <artifactId>org.glassfish.jersey.ext.jersey-mvc-jsp</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jakarta.servlet.jsp.jstl-api]]
==== *jakarta.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[javax.servlet.jsp.jstl-api]]
==== *javax.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>javaserver pages(tm) standard tag library api</groupId>
    <artifactId>javax.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[javax.servlet.jsp.jstl]]
==== *javax.servlet.jsp.jstl*
**Version**: 1.2.5

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>javax.servlet.jsp.jstl</artifactId>
    <version>1.2.5</version>
</dependency>
----
[[org.glassfish.web.javax.servlet.jsp.jstl]]
==== *org.glassfish.web.javax.servlet.jsp.jstl*
**Version**: 1.2.5

[source,xml]
----
<dependency>
    <groupId>javaserver pages (tm) taglib implementation</groupId>
    <artifactId>org.glassfish.web.javax.servlet.jsp.jstl</artifactId>
    <version>1.2.5</version>
</dependency>
----
[[jspcaching-connector]]
==== *jspcaching-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jspcaching-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.jspcaching-connector]]
==== *fish.payara.server.internal.web.jspcaching-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jsp caching taglib connector module</groupId>
    <artifactId>fish.payara.server.internal.web.jspcaching-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.servlet.jsp-api]]
==== *jakarta.servlet.jsp-api*
**Version**: 2.3.6.payara-p1

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp</groupId>
    <artifactId>jakarta.servlet.jsp-api</artifactId>
    <version>2.3.6.payara-p1</version>
</dependency>
----
[[javax.servlet.jsp-api]]
==== *javax.servlet.jsp-api*
**Version**: 2.3.6.payara-p1

[source,xml]
----
<dependency>
    <groupId>jakarta server pages api</groupId>
    <artifactId>javax.servlet.jsp-api</artifactId>
    <version>2.3.6.payara-p1</version>
</dependency>
----
[[servlet]]
=== `servlet`

[[jaspic-servlet-utils]]
==== *jaspic-servlet-utils*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jaspic-servlet-utils</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.jaspic-servlet-utils]]
==== *fish.payara.server.internal.payara-appserver-modules.jaspic-servlet-utils*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>payara jaspic servlet utilities</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.jaspic-servlet-utils</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.servlet-api]]
==== *jakarta.servlet-api*
**Version**: 4.0.4

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>4.0.4</version>
</dependency>
----
[[jakarta.servlet-api]]
==== *jakarta.servlet-api*
**Version**: 4.0.4

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>4.0.4</version>
</dependency>
----
[[jakarta.servlet-api]]
==== *jakarta.servlet-api*
**Version**: 4.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>4.0.0</version>
</dependency>
----
[[jakarta.servlet-api]]
==== *jakarta.servlet-api*
**Version**: 4.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>4.0.0</version>
</dependency>
----
[[javax.servlet.jsp]]
==== *javax.servlet.jsp*
**Version**: 2.3.4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>javax.servlet.jsp</artifactId>
    <version>2.3.4</version>
</dependency>
----
[[org.glassfish.web.javax.servlet.jsp]]
==== *org.glassfish.web.javax.servlet.jsp*
**Version**: 2.3.4

[source,xml]
----
<dependency>
    <groupId>jsp implementation</groupId>
    <artifactId>org.glassfish.web.javax.servlet.jsp</artifactId>
    <version>2.3.4</version>
</dependency>
----
[[jakarta.servlet.jsp.jstl-api]]
==== *jakarta.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[javax.servlet.jsp.jstl-api]]
==== *javax.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>javaserver pages(tm) standard tag library api</groupId>
    <artifactId>javax.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[javax.servlet.jsp.jstl]]
==== *javax.servlet.jsp.jstl*
**Version**: 1.2.5

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>javax.servlet.jsp.jstl</artifactId>
    <version>1.2.5</version>
</dependency>
----
[[tyrus-container-servlet]]
==== *tyrus-container-servlet*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-servlet</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.container-servlet]]
==== *org.glassfish.tyrus.container-servlet*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus servlet bundle</groupId>
    <artifactId>org.glassfish.tyrus.container-servlet</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[org.glassfish.web.javax.servlet.jsp.jstl]]
==== *org.glassfish.web.javax.servlet.jsp.jstl*
**Version**: 1.2.5

[source,xml]
----
<dependency>
    <groupId>javaserver pages (tm) taglib implementation</groupId>
    <artifactId>org.glassfish.web.javax.servlet.jsp.jstl</artifactId>
    <version>1.2.5</version>
</dependency>
----
[[jersey-cdi1x-servlet]]
==== *jersey-cdi1x-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-servlet</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-servlet</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jakarta.servlet.jsp-api]]
==== *jakarta.servlet.jsp-api*
**Version**: 2.3.6.payara-p1

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp</groupId>
    <artifactId>jakarta.servlet.jsp-api</artifactId>
    <version>2.3.6.payara-p1</version>
</dependency>
----
[[javax.servlet.jsp-api]]
==== *javax.servlet.jsp-api*
**Version**: 2.3.6.payara-p1

[source,xml]
----
<dependency>
    <groupId>jakarta server pages api</groupId>
    <artifactId>javax.servlet.jsp-api</artifactId>
    <version>2.3.6.payara-p1</version>
</dependency>
----
[[jersey-container-servlet-core]]
==== *jersey-container-servlet-core*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet-core</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.]]
==== *org.glassfish.jersey.containers.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-container-servlet-core</groupId>
    <artifactId>org.glassfish.jersey.containers.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[jersey-container-servlet]]
==== *jersey-container-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.containers.]]
==== *org.glassfish.jersey.containers.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-container-servlet</groupId>
    <artifactId>org.glassfish.jersey.containers.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[standardtaglibrary]]
=== `standardtaglibrary`

[[jstl-connector]]
==== *jstl-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jstl-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.web.jstl-connector]]
==== *fish.payara.server.internal.web.jstl-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jstl implementation connector module</groupId>
    <artifactId>fish.payara.server.internal.web.jstl-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.servlet.jsp.jstl-api]]
==== *jakarta.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[jakarta.servlet.jsp.jstl-api]]
==== *jakarta.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[javax.servlet.jsp.jstl-api]]
==== *javax.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>javaserver pages(tm) standard tag library api</groupId>
    <artifactId>javax.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[javax.servlet.jsp.jstl-api]]
==== *javax.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>javaserver pages(tm) standard tag library api</groupId>
    <artifactId>javax.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[javax.servlet.jsp.jstl]]
==== *javax.servlet.jsp.jstl*
**Version**: 1.2.5

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>javax.servlet.jsp.jstl</artifactId>
    <version>1.2.5</version>
</dependency>
----
[[org.glassfish.web.javax.servlet.jsp.jstl]]
==== *org.glassfish.web.javax.servlet.jsp.jstl*
**Version**: 1.2.5

[source,xml]
----
<dependency>
    <groupId>javaserver pages (tm) taglib implementation</groupId>
    <artifactId>org.glassfish.web.javax.servlet.jsp.jstl</artifactId>
    <version>1.2.5</version>
</dependency>
----
[[transaction]]
=== `transaction`

[[jta]]
==== *jta*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>jta</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.transaction.jta]]
==== *fish.payara.server.internal.transaction.jta*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jta implementation for glassfish</groupId>
    <artifactId>fish.payara.server.internal.transaction.jta</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.transaction.jta]]
==== *fish.payara.server.internal.transaction.jta*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jta implementation for glassfish</groupId>
    <artifactId>fish.payara.server.internal.transaction.jta</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.transaction-api]]
==== *jakarta.transaction-api*
**Version**: 1.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.transaction</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
    <version>1.3.3</version>
</dependency>
----
[[jakarta.transaction-api]]
==== *jakarta.transaction-api*
**Version**: 1.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.transaction</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
    <version>1.3.3</version>
</dependency>
----
[[jakarta.transaction-api]]
==== *jakarta.transaction-api*
**Version**: 1.3.3

[source,xml]
----
<dependency>
    <groupId>javax.transaction api</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
    <version>1.3.3</version>
</dependency>
----
[[jakarta.transaction-api]]
==== *jakarta.transaction-api*
**Version**: 1.3.3

[source,xml]
----
<dependency>
    <groupId>javax.transaction api</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
    <version>1.3.3</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-transaction</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction]]
==== *org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-ext-cdi1x-transaction</groupId>
    <artifactId>org.glassfish.jersey.ext.cdi.jersey-cdi1x-transaction</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.transaction.jts]]
==== *fish.payara.server.internal.transaction.jts*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jts implementation for glassfish</groupId>
    <artifactId>fish.payara.server.internal.transaction.jts</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[transaction-internal-api]]
==== *transaction-internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>transaction-internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[transaction-internal-api]]
==== *transaction-internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>transaction-internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.transaction.internal-api]]
==== *fish.payara.server.internal.transaction.internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>transaction service internal api</groupId>
    <artifactId>fish.payara.server.internal.transaction.internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.transaction.internal-api]]
==== *fish.payara.server.internal.transaction.internal-api*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>transaction service internal api</groupId>
    <artifactId>fish.payara.server.internal.transaction.internal-api</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[weld-jta]]
==== *weld-jta*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jta</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[webservices]]
=== `webservices`

[[jackson-module-jaxb-annotations]]
==== *jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.module.jackson-module-jaxb-annotations]]
==== *com.fasterxml.jackson.module.jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson module: old jaxb annotations (javax.xml.bind)</groupId>
    <artifactId>com.fasterxml.jackson.module.jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[opentracing-jaxws]]
==== *opentracing-jaxws*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-jaxws</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[opentracing-jaxws]]
==== *opentracing-jaxws*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-jaxws</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws]]
==== *fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>opentracing jax-ws</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws]]
==== *fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>opentracing jax-ws</groupId>
    <artifactId>fish.payara.server.internal.payara-appserver-modules.opentracing-jaxws</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta xml web services api</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta xml web services api</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.ws.rs-api]]
==== *jakarta.ws.rs-api*
**Version**: 2.1.6

[source,xml]
----
<dependency>
    <groupId>jakarta.ws.rs</groupId>
    <artifactId>jakarta.ws.rs-api</artifactId>
    <version>2.1.6</version>
</dependency>
----
[[jersey-media-jaxb]]
==== *jersey-media-jaxb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-jaxb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[org.glassfish.jersey.media.]]
==== *org.glassfish.jersey.media.*
**Version**: 2.37.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>jersey-media-jaxb</groupId>
    <artifactId>org.glassfish.jersey.media.</artifactId>
    <version>2.37.0.payara-p1</version>
</dependency>
----
[[fish.payara.server.internal.webservices.soap-tcp]]
==== *fish.payara.server.internal.webservices.soap-tcp*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>soap/tcp integration code</groupId>
    <artifactId>fish.payara.server.internal.webservices.soap-tcp</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[webservices-connector]]
==== *webservices-connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>webservices-connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.webservices.connector]]
==== *fish.payara.server.internal.webservices.connector*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>connector for glassfish web services container</groupId>
    <artifactId>fish.payara.server.internal.webservices.connector</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.webservices.metro-glue]]
==== *fish.payara.server.internal.webservices.metro-glue*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>glassfish metro glue code</groupId>
    <artifactId>fish.payara.server.internal.webservices.metro-glue</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.jws-api]]
==== *jakarta.jws-api*
**Version**: 1.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.jws</groupId>
    <artifactId>jakarta.jws-api</artifactId>
    <version>1.1.1</version>
</dependency>
----
[[jakarta.jws-api]]
==== *jakarta.jws-api*
**Version**: 1.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.jws api</groupId>
    <artifactId>jakarta.jws-api</artifactId>
    <version>1.1.1</version>
</dependency>
----
[[org.eclipse.persistence.dbws]]
==== *org.eclipse.persistence.dbws*
**Version**: 2.7.11.payara-p1

[source,xml]
----
<dependency>
    <groupId>eclipselink dbws</groupId>
    <artifactId>org.eclipse.persistence.dbws</artifactId>
    <version>2.7.11.payara-p1</version>
</dependency>
----
[[webservices-osgi]]
==== *webservices-osgi*
**Version**: 2.4.3.payara-p6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-osgi</artifactId>
    <version>2.4.3.payara-p6</version>
</dependency>
----
[[stax2-api]]
==== *stax2-api*
**Version**: 4.2.1

[source,xml]
----
<dependency>
    <groupId>org.codehaus.woodstox</groupId>
    <artifactId>stax2-api</artifactId>
    <version>4.2.1</version>
</dependency>
----
[[stax2-api]]
==== *stax2-api*
**Version**: 4.2.1

[source,xml]
----
<dependency>
    <groupId>stax2 api</groupId>
    <artifactId>stax2-api</artifactId>
    <version>4.2.1</version>
</dependency>
----
[[org.glassfish.metro.webservices-osgi]]
==== *org.glassfish.metro.webservices-osgi*
**Version**: 2.4.3.payara-p6

[source,xml]
----
<dependency>
    <groupId>metro web services runtime osgi bundle</groupId>
    <artifactId>org.glassfish.metro.webservices-osgi</artifactId>
    <version>2.4.3.payara-p6</version>
</dependency>
----
[[fish.payara.server.internal.webservices.jsr109-impl]]
==== *fish.payara.server.internal.webservices.jsr109-impl*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>jsr-109 implementation to deploy metro</groupId>
    <artifactId>fish.payara.server.internal.webservices.jsr109-impl</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta xml binding api</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[webservices.security]]
==== *webservices.security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>webservices.security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[fish.payara.server.internal.security.webservices.security]]
==== *fish.payara.server.internal.security.webservices.security*
**Version**: 5.2022.5

[source,xml]
----
<dependency>
    <groupId>webservices security and jsr 196 implementation</groupId>
    <artifactId>fish.payara.server.internal.security.webservices.security</artifactId>
    <version>5.2022.5</version>
</dependency>
----
[[webservices-extra-jdk-packages]]
==== *webservices-extra-jdk-packages*
**Version**: 2.4.3.payara-p6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-extra-jdk-packages</artifactId>
    <version>2.4.3.payara-p6</version>
</dependency>
----
[[org.glassfish.metro.webservices-extra-jdk-packages]]
==== *org.glassfish.metro.webservices-extra-jdk-packages*
**Version**: 2.4.3.payara-p6

[source,xml]
----
<dependency>
    <groupId>extra jdk 6 packages required by metro web services osgi bundle</groupId>
    <artifactId>org.glassfish.metro.webservices-extra-jdk-packages</artifactId>
    <version>2.4.3.payara-p6</version>
</dependency>
----
[[jaxb-runtime]]
==== *jaxb-runtime*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[txw2]]
==== *txw2*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>txw2</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[jaxb-xjc]]
==== *jaxb-xjc*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-xjc</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[codemodel]]
==== *codemodel*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>codemodel</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[xsom]]
==== *xsom*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>xsom</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[jaxb-jxc]]
==== *jaxb-jxc*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-jxc</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[istack-commons-runtime]]
==== *istack-commons-runtime*
**Version**: 3.0.12

[source,xml]
----
<dependency>
    <groupId>com.sun.istack</groupId>
    <artifactId>istack-commons-runtime</artifactId>
    <version>3.0.12</version>
</dependency>
----
[[istack-commons-tools]]
==== *istack-commons-tools*
**Version**: 3.0.12

[source,xml]
----
<dependency>
    <groupId>com.sun.istack</groupId>
    <artifactId>istack-commons-tools</artifactId>
    <version>3.0.12</version>
</dependency>
----
[[relaxng-datatype]]
==== *relaxng-datatype*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind.external</groupId>
    <artifactId>relaxng-datatype</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[rngom]]
==== *rngom*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind.external</groupId>
    <artifactId>rngom</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[dtd-parser]]
==== *dtd-parser*
**Version**: 1.4.5

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.dtd-parser</groupId>
    <artifactId>dtd-parser</artifactId>
    <version>1.4.5</version>
</dependency>
----
[[fastinfoset]]
==== *fastinfoset*
**Version**: 1.2.18

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.fastinfoset</groupId>
    <artifactId>fastinfoset</artifactId>
    <version>1.2.18</version>
</dependency>
----
[[stax-ex]]
==== *stax-ex*
**Version**: 1.8.3

[source,xml]
----
<dependency>
    <groupId>org.jvnet.staxex</groupId>
    <artifactId>stax-ex</artifactId>
    <version>1.8.3</version>
</dependency>
----
[[jaxb-osgi]]
==== *jaxb-osgi*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-osgi</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[com.sun.xml.bind.jaxb-osgi]]
==== *com.sun.xml.bind.jaxb-osgi*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>jaxb osgi</groupId>
    <artifactId>com.sun.xml.bind.jaxb-osgi</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[webservices-api-osgi]]
==== *webservices-api-osgi*
**Version**: 2.4.3.payara-p6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-api-osgi</artifactId>
    <version>2.4.3.payara-p6</version>
</dependency>
----
[[org.glassfish.metro.webservices-api-osgi]]
==== *org.glassfish.metro.webservices-api-osgi*
**Version**: 2.4.3.payara-p6

[source,xml]
----
<dependency>
    <groupId>metro web services api osgi bundle</groupId>
    <artifactId>org.glassfish.metro.webservices-api-osgi</artifactId>
    <version>2.4.3.payara-p6</version>
</dependency>
----
[[websocket]]
=== `websocket`

[[tyrus-core]]
==== *tyrus-core*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-core</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.core]]
==== *org.glassfish.tyrus.core*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus core</groupId>
    <artifactId>org.glassfish.tyrus.core</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[tyrus-container-glassfish-ejb]]
==== *tyrus-container-glassfish-ejb*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-ejb</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.container-glassfish-ejb]]
==== *org.glassfish.tyrus.container-glassfish-ejb*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus ejb component provider</groupId>
    <artifactId>org.glassfish.tyrus.container-glassfish-ejb</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[tyrus-container-servlet]]
==== *tyrus-container-servlet*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-servlet</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.container-servlet]]
==== *org.glassfish.tyrus.container-servlet*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus servlet bundle</groupId>
    <artifactId>org.glassfish.tyrus.container-servlet</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[tyrus-container-glassfish-cdi]]
==== *tyrus-container-glassfish-cdi*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-cdi</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.container-glassfish-cdi]]
==== *org.glassfish.tyrus.container-glassfish-cdi*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus cdi component provider</groupId>
    <artifactId>org.glassfish.tyrus.container-glassfish-cdi</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[tyrus-server]]
==== *tyrus-server*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-server</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.server]]
==== *org.glassfish.tyrus.server*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus server</groupId>
    <artifactId>org.glassfish.tyrus.server</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[jakarta.websocket-api]]
==== *jakarta.websocket-api*
**Version**: 1.1.2

[source,xml]
----
<dependency>
    <groupId>jakarta.websocket</groupId>
    <artifactId>jakarta.websocket-api</artifactId>
    <version>1.1.2</version>
</dependency>
----
[[javax.websocket-api]]
==== *javax.websocket-api*
**Version**: 1.1.2

[source,xml]
----
<dependency>
    <groupId>jakarta websocket - server api</groupId>
    <artifactId>javax.websocket-api</artifactId>
    <version>1.1.2</version>
</dependency>
----
[[tyrus-client]]
==== *tyrus-client*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-client</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.client]]
==== *org.glassfish.tyrus.client*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus client</groupId>
    <artifactId>org.glassfish.tyrus.client</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[tyrus-spi]]
==== *tyrus-spi*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-spi</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.spi]]
==== *org.glassfish.tyrus.spi*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus container spi</groupId>
    <artifactId>org.glassfish.tyrus.spi</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[tyrus-container-grizzly-client]]
==== *tyrus-container-grizzly-client*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-grizzly-client</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[org.glassfish.tyrus.container-grizzly-client]]
==== *org.glassfish.tyrus.container-grizzly-client*
**Version**: 1.20.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>tyrus grizzly client container</groupId>
    <artifactId>org.glassfish.tyrus.container-grizzly-client</artifactId>
    <version>1.20.0.payara-p1</version>
</dependency>
----
[[xmlregistries]]
=== `xmlregistries`

[[jakarta.xml.registry-api]]
==== *jakarta.xml.registry-api*
**Version**: 1.0.10

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.registry</groupId>
    <artifactId>jakarta.xml.registry-api</artifactId>
    <version>1.0.10</version>
</dependency>
----
[[javax.xml.registry-api]]
==== *javax.xml.registry-api*
**Version**: 1.0.10

[source,xml]
----
<dependency>
    <groupId>javax.xml.registry api</groupId>
    <artifactId>javax.xml.registry-api</artifactId>
    <version>1.0.10</version>
</dependency>
----
[[xmlrpc]]
=== `xmlrpc`

[[jackson-dataformat-xml]]
==== *jackson-dataformat-xml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-dataformat-xml]]
==== *jackson-dataformat-xml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.dataformat.jackson-dataformat-xml]]
==== *com.fasterxml.jackson.dataformat.jackson-dataformat-xml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-dataformat-xml</groupId>
    <artifactId>com.fasterxml.jackson.dataformat.jackson-dataformat-xml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.dataformat.jackson-dataformat-xml]]
==== *com.fasterxml.jackson.dataformat.jackson-dataformat-xml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-dataformat-xml</groupId>
    <artifactId>com.fasterxml.jackson.dataformat.jackson-dataformat-xml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.module.jackson-module-jaxb-annotations]]
==== *com.fasterxml.jackson.module.jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson module: old jaxb annotations (javax.xml.bind)</groupId>
    <artifactId>com.fasterxml.jackson.module.jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[com.fasterxml.jackson.core.]]
==== *com.fasterxml.jackson.core.*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-databind</groupId>
    <artifactId>com.fasterxml.jackson.core.</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta xml web services api</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta xml web services api</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[com.fasterxml.jackson.core.jackson-annotations]]
==== *com.fasterxml.jackson.core.jackson-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-annotations</groupId>
    <artifactId>com.fasterxml.jackson.core.jackson-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jakarta.xml.registry-api]]
==== *jakarta.xml.registry-api*
**Version**: 1.0.10

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.registry</groupId>
    <artifactId>jakarta.xml.registry-api</artifactId>
    <version>1.0.10</version>
</dependency>
----
[[com.fasterxml.classmate]]
==== *com.fasterxml.classmate*
**Version**: 1.5.0

[source,xml]
----
<dependency>
    <groupId>classmate</groupId>
    <artifactId>com.fasterxml.classmate</artifactId>
    <version>1.5.0</version>
</dependency>
----
[[javax.xml.registry-api]]
==== *javax.xml.registry-api*
**Version**: 1.0.10

[source,xml]
----
<dependency>
    <groupId>javax.xml.registry api</groupId>
    <artifactId>javax.xml.registry-api</artifactId>
    <version>1.0.10</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta xml binding api</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta xml binding api</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[com.fasterxml.jackson.core.jackson-core]]
==== *com.fasterxml.jackson.core.jackson-core*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-core</groupId>
    <artifactId>com.fasterxml.jackson.core.jackson-core</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jakarta.xml.rpc-api]]
==== *jakarta.xml.rpc-api*
**Version**: 1.1.4

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.rpc</groupId>
    <artifactId>jakarta.xml.rpc-api</artifactId>
    <version>1.1.4</version>
</dependency>
----
[[jakarta.xml.rpc-api]]
==== *jakarta.xml.rpc-api*
**Version**: 1.1.4

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.rpc</groupId>
    <artifactId>jakarta.xml.rpc-api</artifactId>
    <version>1.1.4</version>
</dependency>
----
[[javax.xml.rpc-api]]
==== *javax.xml.rpc-api*
**Version**: 1.1.4

[source,xml]
----
<dependency>
    <groupId>jakarta xml rpc api</groupId>
    <artifactId>javax.xml.rpc-api</artifactId>
    <version>1.1.4</version>
</dependency>
----
[[javax.xml.rpc-api]]
==== *javax.xml.rpc-api*
**Version**: 1.1.4

[source,xml]
----
<dependency>
    <groupId>jakarta xml rpc api</groupId>
    <artifactId>javax.xml.rpc-api</artifactId>
    <version>1.1.4</version>
</dependency>
----
[[com.sun.xml.bind.jaxb-osgi]]
==== *com.sun.xml.bind.jaxb-osgi*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>jaxb osgi</groupId>
    <artifactId>com.sun.xml.bind.jaxb-osgi</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[com.fasterxml.woodstox.woodstox-core]]
==== *com.fasterxml.woodstox.woodstox-core*
**Version**: 5.4.0

[source,xml]
----
<dependency>
    <groupId>woodstox</groupId>
    <artifactId>com.fasterxml.woodstox.woodstox-core</artifactId>
    <version>5.4.0</version>
</dependency>
----
[[com.fasterxml.jackson.dataformat.jackson-dataformat-yaml]]
==== *com.fasterxml.jackson.dataformat.jackson-dataformat-yaml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>jackson-dataformat-yaml</groupId>
    <artifactId>com.fasterxml.jackson.dataformat.jackson-dataformat-yaml</artifactId>
    <version>2.13.4</version>
</dependency>
----
